= WildFly Swarm Initial Release
bobmcwhirter
2015-05-05
:revdate: 2015-05-05 16:16:16 -0500
:awestruct-tags: [announcement, release, swarm]
:awestruct-layout: blog
:source-highlighter: coderay

Happy Cinco De Mayo!  

Crack open a cold adult beverage and start retooling your JavaEE skills 
towards microservices. 

WildFly Swarm footnote:[never to be called just "Swarm", because Legal] is a 
new sidecar project supporting WildFly 9.x to enable
deconstructing the WildFly AS and pasting just enough of it back together
with your application to create a self-contained executable jar.


I'm happy to announce the link:{base_url}/downloads/[beta release of WildFly 9]! WildFly 9 builds off of WildFly 8's Java EE7 support, and adds many new capabilities, including intelligent load balancing, HTTP/2 support, a new offline CLI mode, graceful single node shutdown, and a new Servlet-only distribution. For more details, check out the link:https://developer.jboss.org/wiki/WildFly900Beta1ReleaseNotes[full release notes].

Provided no major issues are discovered, we plan to move to CR fairly quickly, sometime in April. 

Enjoy!
