= WildFly 10 Final is now available!
jgreene
2016-01-29
:revdate: 2016-01-29 22:00:00 -0600
:awestruct-tags: [announcement, release]
:awestruct-layout: blog
:source-highlighter: coderay

WildFly 10 Final is officially complete and available link:{base_url}/downloads[for download]! WildFly 10 adds a number of capabilities and improvements to the powerful, yet lightweight, open-source application server.
 
Java EE 7
---------
As with WildFly 8 and WildFly 9, WildFly 10 implements the Java EE 7 Full and Web Profile standards.


Builds on WildFly 9
-------------------
In addition to the key features mentioned below, this release includes all the major features from 9, such as link:http://wildfly.org/news/2015/07/02/WildFly9-Final-Released/[HTTP/2 support and a built in load-balancer].


Java 8+
-------
Java 7 support has been discontinued allowing for deeper integration with the Java 8 runtime. While Java 9 is still in development, this release runs on the current development snapshots.
 
 
ActiveMQ Artemis
---------------- 
A little over a year ago, the HornetQ codebase was donated to the Apache ActiveMQ project, and the HornetQ community joined to build a next-generation messaging broker. This materialized in the link:http://hornetq.blogspot.com/2015/06/hornetq-apache-donation-and-apache.html[first major release of the ActiveMQ Artemis project]. ActiveMQ Artemis includes many new features, and also retains protocol compatibility with the HornetQ broker. WildFly 10 includes this new exciting project as its JMS broker, and due to the protocol compatibility, it fully replaces the HornetQ project.
 
 
Offline CLI Support for Domain Mode
-----------------------------------
In addition to the offline CLI support for standalone mode, you can now launch a host-controller locally within the CLI. Using the embed-host-controller command you can edit the content of domain.xml and host.xml without launching additional processes or opening network sockets.
 
 
JavaScript Support with Hot Reloading
-------------------------------------
WildFly 10 includes the Undertow JS project, which allows you to write server side scripts that can pull in CDI beans and JPA Entity Beans. This can be quite useful for throwing together a quick view layer (perhaps using a templating language like Mustache, or a framework like Angular), or quickly developing a REST endpoint. You can edit the JS files live on the system, and they are dynamically reloaded, without having to redeploy your application.

For more details see the following blog post: link:http://wildfly.org/news/2015/08/10/Javascript-Support-In-Wildfly/[Using Server Side Javascript with Wildfly]


HA Singleton Deployments
------------------------
WildFly 10 adds the ability to deploy a given application as a "singleton deployment". This is a new implementation of a feature that existed in AS 6.0 and earlier. When deployed to a group of clustered servers, a singleton deployment will only deploy on a single node at any given time. If the node on which the deployment is active stops or fails, the deployment will automatically start on another node. The policies for controlling HA singleton behavior are managed by a new "singleton" subsystem.  A deployment may either specify a specific singleton policy or use the default subsystem policy. A deployment identifies itself as singleton deployment via a +/META-INF/singleton-deployment.xml+ deployment descriptor (the schema for which link:https://github.com/wildfly/wildfly/blob/10.0.0.Final/clustering/singleton/extension/src/main/resources/schema/singleton-deployment_1_0.xsd[can be found on GitHub]), which is most easily applied to an existing deployment as a deployment overlay. Alternatively, the requisite singleton configuration can be embedded within an existing +jboss-all.xml+.


HA Singleton MDBs and MDB Delivery Groups
----------------------------------------- 
Another advanced clustering capability in WildFly 10, singleton MDBs supports infrastructures which require message delivery on only single host at a time. In the event of a failure, another host in the cluster with the same application deployed will take over message processing.
 
MDB delivery groups allow an administrator to selectively enable and disable a "delivery group" via a management operation, which is composed of one or more MDBs. This capability supports environments with an external custom failover mechanism. As with all management operations, these calls are accessible from the many management interfaces of WildFly, including the CLI, a Java API, and an HTTP/JSON API.

 
SLSB and MDB Automatic Pool Sizing
----------------------------------
WildFly now pools stateless session beans by default, using a pool size that is computed relative to the size of the IO worker pool, which is itself auto-tuned to match system resources. Additionally MDBs now use a pool which is similarly tuned to a value derived from the number of CPUs on the system. Previously stateless sessions beans did not pool by default, and MDBs used a pool with a small hard-coded size. The values chosen are logged to an INFO message as part of startup. Manual tuning is still supported using the same max-pool-size attribute.
 
Note that the default configurations shipped with WildFly 10 enable automatic pool sizing by using the derive-size attribute. Configurations used with previous versions of WildFly will need to be updated to take advantage of this capability. The intention is to preserve existing behavior as past configurations may have been explicitly tuned to best match deployed applications. While this capability improves the default pool size, achieving maximum performance would likely require specifically setting the size to match the patterns and needs of the application.

 
Migration Operations for Discontinued Subsystems
------------------------------------------------ 
To help users migrating from old subsystems such as jbossweb (AS 7.1), jacorb (WildFly 8), and hornetq (WildFly 9), we have introduced a set of management operations that can convert old configuration over to the new respective subsystem equivalent. Since these operations migrate the underlying management resource model, old CLI scripts or custom provisioning systems can also take advantage of these.

 
Capabilities and Requirements
-----------------------------
Subsystem developers now have the ability to negotiate interaction with other subsystems in a more pluggable way. This allows for subsystems to have dependencies that can be satisfied by more than one subsystem, which is particularly useful in providing multiple implementations of the same underlying capability. Additionally it leads to improved error reporting. Instead of a failure being reported at the service layer, which is how the WildFly runtime is mapped, it is instead reported at a higher level that is easier to connect to the server's configuration. As an example, a missing socket binding is now reported as a missing socket binding, as opposed to a list of services with an unsatisfied dependency. Expect to see overall error reporting in WildFly improve as subsystems begin to adopt this ability.

For more information, link:https://docs.jboss.org/author/display/WFLY10/Working+with+WildFly+Capabilities[see the development guide]. 

 
Hibernate 5
-----------
Hibernate 5 includes several additional improvements, such as greatly improved bytecode enhancement, which is a useful performance optimization. Additionally a number of API improvements are provided, including use of generics in Hibernate Native, and an improved SPI for second level cache providers. Also included are new and improved schema update and validation tooling.

 
Powershell scripts
------------------ 
Powershell scripts ware added to bin directory of WildFly distribution and are meant to fully replace .bat scripts in future releases.
They provide same functionality as .bat scripts and additionally address handful of issues found in batch scripts.

 
WildFly Jira Release Notes
--------------------------
The following table has the complete list of issues resolved against the "full" branch during the development of WildFly 10.

.WildFly 10 Releases
[options="header", cols="18,20,1"]
|==========================
|Release|Notes|Issues Resolved
|10.0.0.Final   |link:https://issues.jboss.org/jira/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12328857[Full JIRA Release Notes]|71
|10.0.0.CR5   |link:https://issues.jboss.org/jira/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12328604[Full JIRA Release Notes]|156
|10.0.0.CR4   |link:https://issues.jboss.org/jira/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327535[Full JIRA Release Notes]|71
|10.0.0.CR3   |link:https://issues.jboss.org/jira/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12328452[Full JIRA Release Notes]|29
|10.0.0.CR2   |link:https://issues.jboss.org/jira/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327534[Full JIRA Release Notes]|40
|10.0.0.CR1   |link:https://issues.jboss.org/jira/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327161[Full JIRA Release Notes]| 107
|10.0.0.Beta2 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327774[Full JIRA Release Notes]|42
|10.0.0.Beta1 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327160[Full JIRA Release Notes]|63
|10.0.0.Alpha6|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327640[Full JIRA Release Notes]|39
|10.0.0.Alpha5|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327579[Full JIRA Release Notes]|41
|10.0.0.Alpha4|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327286[Full JIRA Release Notes]|37
|10.0.0.Alpha3|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327285[Full JIRA Release Notes]|33
|10.0.0.Alpha2|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327284[Full JIRA Release Notes]|10
|10.0.0.Alpha1|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&amp;version=12327159[Full JIRA Release Notes]|30
|========================== 
 

WildFly Core Jira Release Notes
-------------------------------
The following table has the complete list of issues resolved against the "core" container of WildFly 10.

.WildFly Core 2 Releases
[options="header", cols="18,20,1"]
|==========================
|Release|Notes|Issues Resolve
|2.0.8.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12329400[Full JIRA Release Notes]|26
|2.0.7.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12329385[Full JIRA Release Notes]|2
|2.0.6.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12329259[Full JIRA Release Notes]|9
|2.0.5.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12329068[Full JIRA Release Notes]|9
|2.0.5.CR1|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328936[Full JIRA Release Notes]|19
|2.0.4.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328907[Full JIRA Release Notes]|12
|2.0.3.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328872[Full JIRA Release Notes]|11
|2.0.2.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328667[Full JIRA Release Notes]|16
|2.0.1.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328766[Full JIRA Release Notes]|2
|2.0.0.Final|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328659[Full JIRA Release Notes]|7
|2.0.0.CR9|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328605[Full JIRA Release Notes]|12
|2.0.0.CR7|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328357[Full JIRA Release Notes]|34
|2.0.0.CR6|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328389[Full JIRA Release Notes]|16
|2.0.0.CR5|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328373[Full JIRA Release Notes]|4
|2.0.0.CR4|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328359[Full JIRA Release Notes]|6
|2.0.0.CR2|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328356[Full JIRA Release Notes]|16
|2.0.0.CR1|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328200[Full JIRA Release Notes]|6
|2.0.0.Beta7|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12328164[Full JIRA Release Notes]|20
|2.0.0.Beta6|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12326713[Full JIRA Release Notes]|16
|2.0.0.Beta5|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327877[Full JIRA Release Notes]|21
|2.0.0.Beta4|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327804[Full JIRA Release Notes]|1
|2.0.0.Beta3|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327764[Full JIRA Release Notes]|13
|2.0.0.Beta2|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327763[Full JIRA Release Notes]|5
|2.0.0.Beta1|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12326931[Full JIRA Release Notes]|2
|2.0.0.Alpha13|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327768[Full JIRA Release Notes]|10
|2.0.0.Alpha12|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327666[Full JIRA Release Notes]|4
|2.0.0.Alpha11|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327639[Full JIRA Release Notes]|14
|2.0.0.Alpha10|link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327609[Full JIRA Release Notes]|9
|2.0.0.Alpha9 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327608[Full JIRA Release Notes]|31
|2.0.0.Alpha8 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327607[Full JIRA Release Notes]|9
|2.0.0.Alpha6 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327500[Full JIRA Release Notes]|14
|2.0.0.Alpha5 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327266[Full JIRA Release Notes]|26
|2.0.0.Alpha4 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327265[Full JIRA Release Notes]|10
|2.0.0.Alpha3 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327264[Full JIRA Release Notes]|18
|2.0.0.Alpha2 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12327373[Full JIRA Release Notes]|4
|2.0.0.Alpha1 |link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12315422&amp;version=12326712[Full JIRA Release Notes]|12
|================
