= WildFly 11 Final is now available!
jgreene
2017-10-23
:revdate: 2017-10-23 23:00:00 -0600
:awestruct-tags: [announcement, release]
:awestruct-layout: blog
:source-highlighter: coderay

WildFly 11 Final is now available link:{base_url}/downloads[for download]!  The highlights of WildFly 11 are as follows:

Elytron - New Security Infrastructure
-------------------------------------
The biggest change in WildFly 11 is unification on a new common security framework across the full application server.  Previously we had two separate security infrastructures (picketbox and security-realms), each covering separate use cases, and largely operating independent of the other. In addition to unification, Elytron brings a number of advanced capabilities such as privilege propagation across multiple service invocations, identity switching, pre-request TLS verification, and rich security policies. Finally, it improves the overall extensibility of the system allowing for tight integration with SSO / IDP systems such as KeyCloak. 

While WildFly 11 introduces a new security infrastructure, the existing security-domain and security-realm configurations and APIs are all present and internally mapped to Elytron. To further ease the impact of this change, WildFly 11’s default configurations still use the legacy security-domains and security-realms. A subsequent release will convert the default configurations over to the new configuration model. 

For more information see the Elytron documentation:
https://docs.jboss.org/author/display/WFLY/WildFly+Elytron+Security

As well as the section on migration:
https://docs.jboss.org/author/display/WFLY/Migrate+Legacy+Security+to+Elytron+Security

Simplified EJB / Naming Proxies
-------------------------------
JNDI and EJB invocation have both been simplified and enhanced in WildFly 11. There is a new naming client library, WildFly Naming Client that allows you to easily configure access to WildFly with minimal properties and configuration. EJBs (and other resources) can be accessed in a dynamic discovery mode, or alternatively, in a new point to point mode that locks all EJB proxies to a specified address. This replaces the previous scoped context feature with more intuitive semantics that are ideal for ad-hoc behavior. Additionally, with the new Elytron authentication infrastructure, the user identity can now be changed in-between requests. Finally, older clients from past WildFly releases can still be used with WildFly 11. 

See the following for more information on the new WildFly Naming client: +
https://github.com/wildfly/wildfly-naming-client

Request oriented EJB/JNDI over HTTP
-----------------------------------
Since WildFly 8, all protocols (with the exception of IIOP) can utilize HTTP Upgrade to communicate over a reduced set of ports on the server (one for management, and one for applications). However, since HTTP Upgrade converts the connection to the native protocol used, any HTTP load-balancers acting as an intermediary can only balance on initial connection establishment. To allow for balancing at the individual invocation level, a new “pure” HTTP protocol was added. Clients which utilize http:// URLs as opposed to remoting+http:// will obtain this new behavior. Since this protocol utilizes standard HTTP behavior, it can be efficiently balanced by any load-balancer, not just the one built into WildFly. 

WildFly OpenSSL & HTTP/2
------------------------

WildFly 11 now provides a JSSE provider that can offload TLS handling from the JVM’s internal implementation to an OpenSSL library on your system, typically improving TLS performance. If the version discovered and/or specified is 1.0.2 or greater, then WildFly will utilize OpenSSL’s ALPN support to provide HTTP/2 support. HTTP/2 support will be disabled on versions less than 1.0.2.

Note that HTTP/2 is also supported without OpenSSL, out of the box, on Java 8 (on VMs derived from OpenJDK) and Java 9 (using the new standard ALPN API). 

You can enable OpenSSL in the default configurations with the following CLI command:

[source]
----
/core-service=management/security-realm=ApplicationRealm/server-identity=ssl:write-attribute(name=protocol,value=openssl.TLS)
----

If your openssl library is not installed in a standard location, you will need to additionally set the +org.wildfly.openssl.path+ system property to point to the location of the library:

[source]
----
-Dorg.wildfly.openssl.path=/path/to/dir/with/openssl/lib
----

New Load-Balancer Configs
-------------------------
In order to simplify the setup of WildFly as an HTTP load-balancer, there is an additional +standalone-load-balancer.xml+ configuration in the distribution, which is an instance slimmed to just running the load balancing services. Additionally the stock +domain.xml+ also includes this as a profile configuration that can be referenced by server groups. 

Graceful Shutdown/Startup Improvements
--------------------------------------
Distributed transactions are now handled by the graceful shutdown mechanism. Existing transactions will allow local operations to continue, but any new in-flowed transaction will be rejected. Additionally there is a new EJB parameter that allows for additional remote calls to occur against an established/active remote transaction. Finally you can now start the server directly in suspended mode, for staging changes. This is now part of the default start sequence where the server enters suspend first, and then resumes after all services have launched, so new requests aren’t accepted during the brief window of the server starting.


Web Console Improvements
-------------------------
A number of Web Console improvements are included in WildFly 11, including the ability to see recent configuration changes, to manage active JMS transactions, manage active batch jobs, manage Undertow filters, and test data-sources during creation.  

Management and Configuration Improvements
-----------------------------------------
WildFly 11 now supports remote managed exploded deployments, which allows remote management clients the ability to update content within the deployment, such as html and jsp files without requiring a full redeployment. Additionally there is a new management operation that can be used to read individual files in any deployment. In addition to these new capabilities, errors in the XML now lead to pretty printed easier to understand error messages,

Also notable is that CLI tab completion can now tab complete attribute reference values that have capabilities present, such as references to socket bindings.  Finally, there is a new SPI for server extensions, that can be used to register a process state listener, and react to server life-cycle changes (such as the server stopping).

Further Reading
---------------
In the run-up to the release, we have been blogging about WildFly 11's features. These articles contain detailed information and useful tips on how take advantage of these capabilities, so be sure to take a look!

.Recent Articles
[cols="1,3",options="header"]
|===
|Author | Title 
|Emmanuel Hugonnet|http://wildfly.org/news/2017/09/08/Exploded-deployments/[Using exploded deployments and CLI attachments]
|Farah Juma|https://developer.jboss.org/people/fjuma/blog/2017/09/08/getting-started-with-ejbs-and-elytron-part-1[How to secure EJBs with Elytron and invoke them from remote clients]
|Farah Juma|https://developer.jboss.org/people/fjuma/blog/2017/09/08/getting-started-with-ejbs-and-elytron-part-2[EJB invocations from remote servers]
|Farah Juma|https://developer.jboss.org/people/fjuma/blog/2017/09/28/how-to-use-an-elytron-sasl-plus-mechanism[How to use an Elytron SASL mechanism that supports channel binding]
|Claudio Miranda|http://claudius.com.br/2017/09/wildfly-11-web-console-new-features[Admin/Web Console Features & Enhancements]
|Darran Lofthouse|http://darranl.blogspot.ch/2017/09/wildfly-elytron-add-kerberos.html[WildFly Elytron - Add Kerberos Authentication to Existing Web Application]
|Darran Lofthouse|http://darranl.blogspot.ch/2017/09/using-wildfly-elytron-with-undertow.html[Using WildFly Elytron with Undertow Standalone]
|Brian Stansberry|http://wildfly.org/news/2017/09/29/Management-model-referential-integrity/[Management Model Referential Integrity and Suggestions]
|Jeff Mesnil|http://wildfly.org/news/2017/10/03/Messaging-features/[Messaging features in WildFly 11]
|Stuart Douglas|http://wildfly.org/news/2017/10/06/OpenSSL-Support-In-Wildfly/[OpenSSL & HTTP/2]
|Ken Wills|http://wildfly.org/news/2017/10/09/Embedded-Host-Controller/[Embedded Hostcontroller]
|===

Jira Release Notes
------------------
The full list of issues resolved is available link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&version=12335280[here].

What's Next
-----------
Now that WildFly 11 is out the door, we plan to move to a faster, more incremental release model, starting with WildFly 12. Expect to see more details here in the future, and as always, your contributions are welcome!
