= Maven Plugin
:awestruct-layout: project

== Fractions

Fractions within WildFly Swarm are roughly equivalent to
subsystems within WildFly.  Each fraction is matched by a
Maven-addressible dependency that you may include into your
project.

By simply adding the fraction as a dependency, when you boot
your WildFly Swarm-based app, the appropriate extensions and
subsystems will be mixed into your container without any
explicit configuration or code required.

== Configuring fractions

If you don't enjoy the default configuration, you can provide
configuration for any fraction you wish to override.  Any fraction
that you choose not to explicitly configure will continue using
its defaults.

Configuration is through Java APIs.

== List of Fractions

Some fractions may be explicitly pulled in by choice, while others
are mostly used to support other higher-level fractions.

=== bean-validation
=== connector
=== container
=== datasources

Supports the datasources subsystem and its configuration.  Required
if you need to use Java DataSources and deploy JDBC drivers.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-datasources</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== ee
=== io
=== jaxrs

Supports JAX-RS. Provides the JAX-RS spec APIs.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-jaxrs</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== jca
=== jpa

Supports JPA.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-jpa</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== logging

Supports the logging subsystem and its configuration.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-logging</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== messaging

Provides a JMS broker and client APIs.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-messaging</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== msc

Supports JBoss MSC `ServiceActivator` deployments.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-msc</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== naming
=== security
=== transactions

Supports Transactions.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-transactions</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

=== undertow

Supports Servlets and WebSockets.  Provides the appropriate spec APIs.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-undertow</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------
=== weld

Supports CDI via Weld.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-weld</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

== weld-jaxrs

Provides CDI support within JAXRS deployments.

[source,xml]
----------------------------
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-weld-jaxrs</artifactId>
  <version>${version.wildfly-swarm}</version>
<dependency>
----------------------------

