= {simple-microservice-infinispan-part2}
:summary: Java Microservice using WildFly
:includedir: ../_includes
include::{includedir}/_attributes.adoc[]
include::./_includes/_titles.adoc[]
:prerequisites-time: 10

In this post, you will learn HOW-TO run the Docker Image we built in link:simple-microservice-infinispan-part1[{simple-microservice-infinispan-part1}] on Kubernetes.

[[prerequisites]]
== Prerequisites

To complete this guide, you need:

* Complete link:simple-microservice-infinispan-part1[{simple-microservice-infinispan-part1}]

include::_includes/_constants.adoc[]

== Infinispan

We basically will repeat everything we did in link:simple-microservice-part2[{simple-microservice-part2}] but, before, we will deploy Infinispan on Kubernetes;

==== Infinispan configmap

Create e fine named `infinispan-configmap.yaml` with the following content:

.infinispan-configmap.yaml
[source,yaml,subs="normal"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: infinispan-secret
  labels:
    app: infinispan
data:
  USER: {infinispan-user}
  PASS: {infinispan-password}

----

apply the ConfigMap configuration to the Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f infinispan-configmap.yaml
----

==== Infinispan deployment

Create e fine named `infinispan-deployment.yaml` with the following content:

.infinispan-deployment.yaml
[source,yaml,subs="normal"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinispan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinispan
  template:
    metadata:
      labels:
        app: infinispan
    spec:
      containers:
        - name: infinispan
          image: '{infinispan-server-docker-image}'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: infinispan-secret
                  key: USER
            - name: PASS
              valueFrom:
                configMapKeyRef:
                  name: infinispan-secret
                  key: PASS
----

apply the Deployment configuration to the Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f infinispan-deployment.yaml
----

==== Infinispan service

Create e fine named `infinispan-service.yaml` with the following content:

.infinispan-service.yaml
[source,yaml,subs="normal"]
----
apiVersion: v1
kind: Service
metadata:
  name: {infinispan-kubernetes-service-name}
  labels:
    app: infinispan
spec:
  ports:
    - protocol: TCP
      port: 11222
      targetPort: 11222
  selector:
    app: infinispan
----

apply the Service configuration to the Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f infinispan-service.yaml
----

NOTE: if you are using link:https://minikube.sigs.k8s.io/docs/[minikube], and you want to test if Infinispan Server on Kubernetes is working, run `kubectl port-forward svc/{infinispan-kubernetes-service-name} {infinispan-port}:{infinispan-port}`,  then open http://0.0.0.0:{infinispan-port}/console/ in your browser and log in as `{infinispan-user}` / `{infinispan-password}`

== Image Registry

To make the `{my-jaxrs-app-infinispan-docker-image-name}:latest` Docker Image available to Kubernetes, you need to push it to some Image Registry that is accessible by the Kubernetes cluster you want to use;

=== Quay.io

There are many options to achieve this; in this post, we will push the `{my-jaxrs-app-infinispan-docker-image-name}:latest` Docker Image, to the link:quay.io[quay.io] Image Registry;

NOTE: You can skip this step in case you prefer to re-use the `quay.io/{quay-io-account-name}/{my-jaxrs-app-infinispan-docker-image-name}` Docker Image, that we already pushed to link:quay.io[quay.io] in the `{quay-io-account-name}` account;

Create a public repository named `{my-jaxrs-app-infinispan-docker-image-name}` on link:quay.io[quay.io] (e.g. link:https://quay.io/repository/{quay-io-account-name}/my-jaxrs-app-infinispan[https://quay.io/repository/{quay-io-account-name}/my-jaxrs-app-infinispan]);

NOTE: replace `{quay-io-account-name}` with the name of your account in all the commands that will follow

Tag the Docker image:

[source,bash,subs="normal"]
----
podman tag {my-jaxrs-app-infinispan-docker-image-name} quay.io/{quay-io-account-name}/{my-jaxrs-app-infinispan-docker-image-name}
----

Push the `{my-jaxrs-app-infinispan-docker-image-name}` Docker Image to it:

[source,bash,subs="normal"]
----
podman push quay.io/{quay-io-account-name}/{my-jaxrs-app-infinispan-docker-image-name}
----

At this point, the `{my-jaxrs-app-infinispan-docker-image-name}:latest` Docker Image should be publicly available and free to be consumed by any Kubernetes Cluster; you can verify this by running:

[source,bash,subs="normal"]
----
podman pull quay.io/{quay-io-account-name}/{my-jaxrs-app-infinispan-docker-image-name}
----

== Deploy to Kubernetes

To deploy our `{my-jaxrs-app-infinispan-docker-image-name}` Docker Image on link:https://minikube.sigs.k8s.io/docs/[minikube], create a file named `deployment-{my-jaxrs-app-infinispan-docker-image-name}.yaml` (see link:https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[kubernetes deployment]) in the same directory as the `Dockerfile` and the `pom.xml` file, with the following content:

.deployment-{my-jaxrs-app-infinispan-docker-image-name}.yaml
[source,yaml,subs="normal"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {my-jaxrs-app-infinispan-docker-image-name}-deployment
  labels:
    app: {my-jaxrs-app-infinispan-docker-image-name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {my-jaxrs-app-infinispan-docker-image-name}
  template:
    metadata:
      labels:
        app: {my-jaxrs-app-infinispan-docker-image-name}
    spec:
      containers:
      - name: {my-jaxrs-app-infinispan-docker-image-name}
        image: quay.io/{quay-io-account-name}/{my-jaxrs-app-infinispan-docker-image-name}
        ports:
        - containerPort: 8080
        - containerPort: 9990
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9990
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9990
        startupProbe:
          httpGet:
            path: /health/started
            port: 9990
        env:
        - name: INFINISPAN_SERVER_HOST
          value: {infinispan-kubernetes-service-name}
        - name: INFINISPAN_SERVER_PORT
          value: '{infinispan-port}'
        - name: INFINISPAN_SERVER_USER
          valueFrom:
            configMapKeyRef:
              name: infinispan-secret
              key: USER
        - name: INFINISPAN_SERVER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: infinispan-secret
              key: PASS
----

apply the Deployment configuration to the Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f deployment-{my-jaxrs-app-infinispan-docker-image-name}.yaml
----

We used to link:https://minikube.sigs.k8s.io/docs/[minikube] as Kubernetes Cluster, hence we expose the deployment as `NodePort`:

[source,bash,subs="normal"]
----
kubectl expose deployment.apps/{my-jaxrs-app-infinispan-docker-image-name}-deployment --type=NodePort --port=8080
----

=== Check the application

Find out on what IP, link:https://minikube.sigs.k8s.io/docs/[minikube] is exposing your service:

[source,bash,subs="normal"]
----
$ minikube service {my-jaxrs-app-infinispan-docker-image-name}-deployment --url
http://192.168.39.143:31076
----

Open link:http://192.168.39.143:31076/[http://192.168.39.143:31076/] in your Browser, enter some name in the `Name` field (e.g. "*pippo*") and press `Say Hello`".

Stop the application:

[source,bash,subs="normal"]
----
kubectl scale deploy {my-jaxrs-app-infinispan-docker-image-name}-deployment --replicas=0
----

Start the application once again:

[source,bash,subs="normal"]
----
kubectl scale deploy {my-jaxrs-app-infinispan-docker-image-name}-deployment --replicas=1
----

Type a different name in the `Name` field and press `Say Hello` again: the page should display something like "*last time you were pippo*" and that means that the previous name was stored in the Infinispan Server;

== What's next?

link:simple-microservice-jms-part1[{simple-microservice-jms-part1}]

[[references]]
== References

* Source code for this post: {source-code-git-repository}/tree/simple-microservice-infinispan-part2

Back to Guides

< link:../get-started-microservices-on-kubernetes[Back to Getting Started with WildFly micro-services on Kubernetes]