= {simple-microservice-database-part2}
:summary: Java Microservice using WildFly
:includedir: ../_includes
include::{includedir}/_attributes.adoc[]
include::./_includes/_titles.adoc[]
:prerequisites-time: 10

In this guide, you will learn HOW-TO run the Docker Image we built in link:simple-microservice-database-part1[{simple-microservice-database-part1}] on Kubernetes.

[[prerequisites]]
== Prerequisites

To complete this guide, you need:

* Complete link:simple-microservice-database-part1[{simple-microservice-database-part1}]

include::_includes/_constants.adoc[]

== Database

=== PostgreSQL

We basically will repeat everything we did in link:simple-microservice-part2[{simple-microservice-part2}] but, before, we will deploy PostgreSQL on Kubernetes.

==== PostgreSQL configmap

Create the file named `postgres-configmap.yaml` with the following content:

.postgres-configmap.yaml
[source,yaml,subs="normal"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRESQL_USER: {postgre-sql-user}
  POSTGRESQL_PASSWORD: {postgre-sql-password}
  POSTGRESQL_HOST: {postgre-sql-kubernetes-service-name}
  POSTGRESQL_PORT: "{postgre-sql-port}"
  POSTGRESQL_DATABASE: {postgre-sql-database}
  POSTGRESQL_JNDI: {postgre-sql-jndi}
----

apply the ConfigMap configuration to Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f postgres-configmap.yaml
----

==== PostgreSQL deployment

Create the file named `postgres-deployment.yaml` with the following content:

.postgres-deployment.yaml
[source,yaml,subs="normal"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: '{postgre-docker-image}'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {postgre-sql-port}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRESQL_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRESQL_DATABASE
----

apply the Deployment configuration to Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f postgres-deployment.yaml
----

==== PostgreSQL service

Create a file named `postgres-service.yaml` with the following content:

.postgres-service.yaml
[source,yaml,subs="normal"]
----
apiVersion: v1
kind: Service
metadata:
  name: {postgre-sql-kubernetes-service-name}
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: {postgre-sql-port}
      targetPort: {postgre-sql-port}
  selector:
    app: postgres
----

apply the Service configuration to Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f postgres-service.yaml
----

NOTE: if you are using link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"], and you want to test if PostgreSQL is working, run `kubectl port-forward svc/{postgre-sql-kubernetes-service-name} {postgre-sql-port}:{postgre-sql-port}` and then connect via JDBC using URL `jdbc:postgresql://{postgre-sql-host}:{postgre-sql-port}/{postgre-sql-database}`

== Image Registry

To make the `{my-jaxrs-app-db-docker-image-name}:latest` Docker Image available to Kubernetes, you need to push it to some Image Registry that is accessible by the Kubernetes cluster you want to use.

=== Quay.io

There are many Image Registries you can use: in this guide, we will push the `{my-jaxrs-app-db-docker-image-name}:latest` Docker Image, to the link:https://quay.io[quay.io, window="_blank"] Image Registry.

Create a public repository named `{my-jaxrs-app-db-docker-image-name}` on link:https://quay.io[quay.io, window="_blank"] (e.g. link:https://quay.io/repository/{quay-io-account-name}/my-jaxrs-app-db[https://quay.io/repository/{quay-io-account-name}/my-jaxrs-app-db, window="_blank"]).

NOTE: replace `{quay-io-account-name}` with the name of your account in all the commands that will follow

Tag the Docker image:

[source,bash,subs="normal"]
----
podman tag {my-jaxrs-app-db-docker-image-name} quay.io/{quay-io-account-name}/{my-jaxrs-app-db-docker-image-name}
----

Push the `{my-jaxrs-app-db-docker-image-name}` Docker Image to it:

[source,bash,subs="normal"]
----
podman push quay.io/{quay-io-account-name}/{my-jaxrs-app-db-docker-image-name}
----

At this point, the `{my-jaxrs-app-db-docker-image-name}:latest` Docker Image should be publicly available and free to be consumed by any Kubernetes Cluster; you can verify this by running:

[source,bash,subs="normal"]
----
podman pull quay.io/{quay-io-account-name}/{my-jaxrs-app-db-docker-image-name}
----

== Deploy to Kubernetes

To deploy our `{my-jaxrs-app-db-docker-image-name}` Docker Image on link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"], create a file named `deployment-{my-jaxrs-app-db-docker-image-name}.yaml` (see link:https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[kubernetes deployment, window="_blank"]) in the same directory as the `Dockerfile` and the `pom.xml` file, with the following content:

.deployment-{my-jaxrs-app-db-docker-image-name}.yaml
[source,yaml,subs="normal"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {my-jaxrs-app-db-docker-image-name}-deployment
  labels:
    app: {my-jaxrs-app-db-docker-image-name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {my-jaxrs-app-db-docker-image-name}
  template:
    metadata:
      labels:
        app: {my-jaxrs-app-db-docker-image-name}
    spec:
      containers:
      - name: {my-jaxrs-app-db-docker-image-name}
        image: quay.io/{quay-io-account-name}/{my-jaxrs-app-db-docker-image-name}
        ports:
        - containerPort: 8080
        - containerPort: 9990
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9990
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9990
        startupProbe:
          httpGet:
            path: /health/started
            port: 9990
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRESQL_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRESQL_PASSWORD
        - name: POSTGRESQL_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRESQL_HOST
        - name: POSTGRESQL_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRESQL_PORT
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRESQL_DATABASE
        - name: POSTGRESQL_JNDI
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRESQL_JNDI
----

apply the Deployment configuration to Kubernetes:

[source,bash,subs="normal"]
----
kubectl apply -f deployment-{my-jaxrs-app-db-docker-image-name}.yaml
----

We used link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"] as Kubernetes Cluster, hence we expose the deployment as `NodePort`:

[source,bash,subs="normal"]
----
kubectl expose deployment.apps/{my-jaxrs-app-db-docker-image-name}-deployment --type=NodePort --port=8080
----

=== Check the application

Find out on what IP address/port, link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"] is exposing your service:

[source,bash,subs="normal"]
----
$ minikube service {my-jaxrs-app-db-docker-image-name}-deployment --url
http://192.168.39.143:30433
----

Just like we did before, hit the following URLs, using a utility like `curl`:

.Insert some Data into the Database:
[source,bash]
----
$ curl -X POST http://192.168.39.143:30433/hello/test-table/somedata1/somedata2
{"field1":"somedata1","field2":"somedata2","id":1}
----

.Query the database to show the inserted data:
[source,bash]
----
$ curl http://192.168.39.143:30433/hello/test-table
[{"field1":"somedata1","field2":"somedata2","id":1}]
----

== What's next?

link:simple-microservice-infinispan-part1[{simple-microservice-infinispan-part1}]

[[references]]
== References

* Source code for this guide: {source-code-git-repository}/tree/simple-microservice-database-part2

Back to Guides

< link:../get-started-microservices-on-kubernetes[Back to Getting Started with WildFly micro-services on Kubernetes]