= {simple-microservice-part2}
:summary: ONELINE EXPLANATION OF THE GUIDE
:includedir: ../_includes
include::{includedir}/_attributes.adoc[]
include::./_includes/_titles.adoc[]
// you can override any attributes eg to lengthen the
// time to complete the guide
:prerequisites-time: 10

In this post, you will learn HOW-TO run the Docker Image you built in link:simple-microservice-part1[{simple-microservice-part1}] on Kubernetes.

[[prerequisites]]
== Prerequisites

To complete this guide, you need:

* Complete link:simple-microservice-part1[{simple-microservice-part1}]
* A link:https://kubernetes.io[Kubernetes, window="_blank"] cluster: throughout this mini-series, we will use link:https://minikube.sigs.k8s.io[Minikube, window="_blank"]

include::_includes/_constants.adoc[]

== Image Registry

To make the `{my-jaxrs-app-docker-image-name}:latest` Docker Image available to Kubernetes, you need to push it to some Image Registry that is accessible by the Kubernetes cluster you want to use;

=== Quay.io

There are many options to achieve this; in this post, we will push the `{my-jaxrs-app-docker-image-name}:latest` Docker Image, to the link:https://quay.io[quay.io, window="_blank"] Image Registry;

NOTE: You can skip this step in case you prefer to re-use the Docker Image that is already available at link:https://quay.io/repository/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}[quay.io/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}, window="_blank"];

Create a public repository named `{my-jaxrs-app-docker-image-name}` on link:https://quay.io[quay.io, window="_blank"] (e.g. link:https://quay.io/repository/{quay-io-account-name}/my-jaxrs-app[https://quay.io/repository/{quay-io-account-name}/my-jaxrs-app, window="_blank"]);

NOTE: replace `{quay-io-account-name}` with the name of your account in all the commands that will follow

Tag the Docker image:

[source,bash,subs="normal"]
----
podman tag {my-jaxrs-app-docker-image-name} quay.io/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}
----

Push the `{my-jaxrs-app-docker-image-name}` Docker Image to it:

[source,bash,subs="normal"]
----
podman push quay.io/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}
----

At this point, the `{my-jaxrs-app-docker-image-name}:latest` Docker Image should be publicly available and free to be consumed by any Kubernetes Cluster; you can verify this by running:

[source,bash,subs="normal"]
----
podman pull quay.io/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}
----

== Kubernetes

=== Minikube

You can use whatever Kubernetes cluster you have available; in this post, and in the following, we will use link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"];

=== Deploy to Kubernetes

To deploy our `quay.io/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}` Docker image to Kubernetes, create a file named `deployment-{my-jaxrs-app-docker-image-name}.yaml` (see link:https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[kubernetes deployment, window="_blank"]) in the same directory as the `Dockerfile` and the `pom.xml` file, with the following content:

.deployment-{my-jaxrs-app-docker-image-name}.yaml
[source,yaml,subs="normal"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {my-jaxrs-app-docker-image-name}-deployment
  labels:
    app: {my-jaxrs-app-docker-image-name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {my-jaxrs-app-docker-image-name}
  template:
    metadata:
      labels:
        app: {my-jaxrs-app-docker-image-name}
    spec:
      containers:
      - name: {my-jaxrs-app-docker-image-name}
        image: quay.io/{quay-io-account-name}/{my-jaxrs-app-docker-image-name}
        ports:
        - containerPort: 8080
        - containerPort: 9990
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9990
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9990
        startupProbe:
          httpGet:
            path: /health/started
            port: 9990

----

Deploy to your Kubernetes Cluster:

[source,bash,subs="normal"]
----
$ kubectl apply -f deployment-{my-jaxrs-app-docker-image-name}.yaml
deployment.apps/{my-jaxrs-app-docker-image-name}-deployment created
----

We used link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"] as Kubernetes Cluster, hence we expose the deployment as `NodePort`:

[source,bash,subs="normal"]
----
$ kubectl expose deployment.apps/{my-jaxrs-app-docker-image-name}-deployment --type=NodePort --port=8080
service/{my-jaxrs-app-docker-image-name}-deployment exposed
----

NOTE: you can also use link:https://docs.wildfly.org/wildfly-charts/[Helm Chart for WildFly, window="_blank"] to deploy your application

=== Check your application

Find out on what IP, link:https://minikube.sigs.k8s.io/docs/[minikube, window="_blank"] is exposing your service:

[source,bash,subs="normal"]
----
$ minikube service {my-jaxrs-app-docker-image-name}-deployment --url
http://192.168.39.139:30782
----

Verify it's working as expected:

[source,bash,subs="normal"]
----
$ curl http://192.168.39.139:30782/hello/pippo
Hello 'pippo'.
----

== What's next?

link:simple-microservice-database-part1[{simple-microservice-database-part1}]

[[references]]
== References

* Source code for this post: {source-code-git-repository}/tree/simple-microservice-part2

< link:../get-started-microservices-on-kubernetes[Back to Getting Started with WildFly micro-services on Kubernetes]