= {simple-microservice-jms-part1}
:summary: Java Microservice using WildFly
:includedir: ../_includes
include::{includedir}/_attributes.adoc[]
include::./_includes/_titles.adoc[]
:prerequisites-time: 10

In this post, we will extend the example created in link:simple-microservice-part1[{simple-microservice-part1}] and add an external JMS broker connectivity;

[[prerequisites]]
== Prerequisites

To complete this guide, you need:

* Complete link:simple-microservice-part1[{simple-microservice-part1}]

include::_includes/_constants.adoc[]

== External JMS broker 

=== Apache Artemis

We will use Apache Artemis in this post in its containerized version: see link:https://quay.io/artemiscloud/activemq-artemis-broker-kubernetes[Artemis Official Image];

Start Apache Artemis:

[source,bash,subs="normal"]
----
podman netwrok create {podman-network-name}

podman run --rm --name {artemis-pod-name} \
    --network={podman-network-name} \
    -p {artemis-console-port}:{artemis-console-port} \
    -p {artemis-port}:{artemis-port}\
    -e AMQ_USER={artemis-user} \
    -e AMQ_PASSWORD={artemis-password} \
    -e AMQ_DATA_DIR=/{artemis-data-path} \
    {artemis-docker-image}
----

NOTE: we started the container with the `--rm`: this way it is disposed automatically when we stop it

NOTE: We started the *{artemis-pod-name}* container with the --network=bridge option: later in this guide, this will allow us to connect to the *{artemis-pod-name}* container from the *{my-jms-app-docker-image-name}* container; 

== Maven Project

=== pom.xml

==== dependencies

Add the following dependencies to the `pom-xml` file `dependencies` section:

[source,xml,subs="normal"]
----
        <dependency>
            <groupId>jakarta.ejb</groupId>
            <artifactId>jakarta.ejb-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.jms</groupId>
            <artifactId>jakarta.jms-api</artifactId>
            <scope>provided</scope>
        </dependency>
----

==== wildfly-maven-plugin

We need to add some features that are necessary when to connect to the broker and to support a Message Driven Bean.

We can add these features by adding the `remote-activemq` layer to our application; add the following to the the link:https://github.com/wildfly/wildfly-maven-plugin/[wildfly-maven-plugin] configuration in the `pom.xml` file:

[source,xml,subs="normal"]
----
    <layers>
        ...
        <layer>ejb</layer>
        <layer>remote-activemq</layer>
        ...
    </layers>
----

You should end up with the link:https://github.com/wildfly/wildfly-maven-plugin/[wildfly-maven-plugin] configured like in the following:

[source,xml,subs="normal"]
----
    <plugin>
        <groupId>org.wildfly.plugins</groupId>
        <artifactId>wildfly-maven-plugin</artifactId>
        <version>{version-wildfly-maven-plugin}</version>
        <configuration>
            <feature-packs>
                <feature-pack>
                    <location>org.wildfly:wildfly-galleon-pack:{version-wildfly-galleon-pack}</location>
                </feature-pack>
                <feature-pack>
                    <location>org.wildfly.cloud:wildfly-cloud-galleon-pack:{version-wildfly-cloud-galleon-pack}</location>
                </feature-pack>
            </feature-packs>
            <layers>
                <layer>cloud-server</layer>
                <layer>ejb</layer>
                <layer>remote-activemq</layer>
            </layers>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>package</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
----


=== Java Classes

Add the following classes to the project:

.org.wildfly.examples.mdb.GettingStartedQueueMDB :
[source,java]
----
package org.wildfly.examples.mdb;

import jakarta.ejb.ActivationConfigProperty;
import jakarta.ejb.MessageDriven;
import jakarta.jms.JMSException;
import jakarta.jms.Message;
import jakarta.jms.MessageListener;
import jakarta.jms.TextMessage;

import java.util.logging.Logger;

@MessageDriven(
        name = "GettingStartedQueueMDB",
        activationConfig = {
            @ActivationConfigProperty(propertyName = "destinationLookup", propertyValue = "queue/gettingStartedQueue"),
            @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "jakarta.jms.Queue"),
            @ActivationConfigProperty(propertyName = "acknowledgeMode", propertyValue = "Auto-acknowledge")}
)
public class GettingStartedQueueMDB implements MessageListener {

    private static final Logger LOGGER = Logger.getLogger(GettingStartedQueueMDB.class.toString());

    public void onMessage(Message rcvMessage) {
        TextMessage msg = null;
        try {
            if (rcvMessage instanceof TextMessage) {
                msg = (TextMessage) rcvMessage;
                LOGGER.info("Received Message from queue: " + msg.getText());
            } else {
                LOGGER.warning("Message of wrong type: " + rcvMessage.getClass().getName());
            }
        } catch (JMSException e) {
            throw new RuntimeException(e);
        }
    }
}

----

.org.wildfly.examples.GettingStartedQueueEndpoint :
[source,java]
----
package org.wildfly.examples;

import jakarta.annotation.Resource;
import jakarta.inject.Inject;
import jakarta.jms.JMSContext;
import jakarta.jms.JMSDestinationDefinition;
import jakarta.jms.JMSDestinationDefinitions;
import jakarta.jms.JMSException;
import jakarta.jms.Queue;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
@JMSDestinationDefinitions(
    value = {
        @JMSDestinationDefinition(
            name = "java:/queue/gettingStartedQueue",
            interfaceName = "jakarta.jms.Queue",
            destinationName = "getting-started-queue",
            properties = {"enable-amq1-prefix=false"}
        )
    }
)
@Path("/message")
public class GettingStartedQueueEndpoint {

    @Resource(lookup="java:/queue/gettingStartedQueue")
    private Queue queue;

    @Inject
    private JMSContext context;

    @GET
    @Path("/send")
    @Produces(MediaType.TEXT_PLAIN)
    public Response sendMessage(final @QueryParam("content") String content) throws JMSException {
        String response = "Sent " + content + " to " + queue.getQueueName();
        context.createProducer().send(queue, content);
        return Response.ok(response).build();
    }
}
----

=== Build the application

[source,bash]
----
$ mvn clean package
...
[INFO] Copy deployment /home/ehugonne/dev/wildfly/guides/get-started-microservices-on-kubernetes/simple-microservice-jms/target/ROOT.war to /home/ehugonne/dev/wildfly/guides/get-started-microservices-on-kubernetes/simple-microservice-jms/target/server/standalone/deployments/ROOT.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.848 s
[INFO] Finished at: 2024-07-18T10:06:17+02:00
[INFO] ------------------------------------------------------------------------
----

=== Start the application


[source,bash,subs="normal"]
----
./target/server/bin/standalone.sh
...
10:11:59,045 INFO  [org.jboss.as.connector.services.resourceadapters.ResourceAdapterActivatorService$ResourceAdapterActivator] (MSC service thread 1-6) IJ020002: Deployed: file://RaActivatoractivemq-ra
10:11:59,046 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-8) WFLYJCA0118: Binding connection factory named java:/JmsXA to alias java:jboss/DefaultJMSConnectionFactory
10:11:59,046 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-5) WFLYJCA0002: Bound Jakarta Connectors ConnectionFactory [java:/JmsXA]
10:11:59,073 INFO  [org.hibernate.validator.internal.util.Version] (MSC service thread 1-7) HV000001: Hibernate Validator 8.0.1.Final
10:11:59,232 INFO  [org.wildfly.extension.messaging-activemq] (MSC service thread 1-5) WFLYMSGAMQ0002: Bound messaging object to jndi name java:/queue/gettingStartedQueue
10:11:59,262 INFO  [org.jboss.weld.Version] (MSC service thread 1-3) WELD-000900: 5.1.2 (Final)
10:11:59,320 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0042: Started message driven bean 'GettingStartedQueueMDB' with 'activemq-ra.rar' resource adapter
10:11:59,651 INFO  [org.wildfly.extension.messaging-activemq] (Thread-1 (ActiveMQ-client-global-threads)) Creating queue getting-started-queue on node UP 01abde48-44d8-11ef-8f51-f2c0ca584945 - TransportConfiguration(name=67e0edf8-44dd-11ef-a580-6ab85081923f, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory)?host=localhost&useNioGlobalWorkerPool=true&port=61616&localAddress=127-0-0-1&useNio=true
10:11:59,845 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 70) RESTEASY002225: Deploying jakarta.ws.rs.core.Application: class org.wildfly.examples.GettingStartedApplication
10:11:59,868 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 70) WFLYUT0021: Registered web context: '/' for server 'default-server'
10:11:59,897 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 38) WFLYSRV0010: Deployed "ROOT.war" (runtime-name : "ROOT.war")
10:11:59,932 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
10:11:59,940 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
10:11:59,940 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
10:11:59,942 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 32.0.1.Final (WildFly Core 24.0.1.Final) started in 2430ms - Started 379 of 547 services (259 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml

----

=== Check the application

Hit the following URLs, using a utility like `curl`:

.Send and consume messages using a queue:
[source,bash]
----
$ curl -X GET http://localhost:8080/hello/message/send?content=Hello%20World
Sent Hello World to getting-started-queue
----

== Docker Image

=== Build the Docker Image

Build the Docker Image with the following command:

[source,bash,subs="normal"]
----
$ podman build -t {my-jms-app-docker-image-name}:latest .
STEP 1/3: FROM quay.io/wildfly/wildfly-runtime:latest
STEP 2/3: COPY --chown=jboss:root target/server $JBOSS_HOME
--> 4609f8ed0c7f
STEP 3/3: RUN chmod -R ug+rwX $JBOSS_HOME
COMMIT my-jms-app:latest
--> db4677f5bf4f
Successfully tagged localhost/my-jms-app:latest
db4677f5bf4f471f5624bd63a21fce3d91b7b3b93e985d3e86a8a4b0682d85cd
----

=== Run the Docker Image

Note that, when running the `{my-jms-app-docker-image-name}:latest` Docker Image:

[source,bash,subs="normal"]
----
podman run --rm --network={podman-network-name} -p 8080:8080 -p 9990:9990 \
    --name={my-jms-app-docker-image-name} \
    -e JBOSS_MESSAGING_CONNECTOR_HOST={artemis-pod-name} \
    {my-jms-app-docker-image-name}:latest

----

NOTE: We started the *{my-jms-app-docker-image-name}* container with the `--network={podman-network-name}` option just like we did when we started the *{artemis-pod-name}* container: the two containers now run in the same *{podman-network-name}* network and we can connect to *{artemis-pod-name}* container from the *{my-jms-app-docker-image-name}* container using the *{artemis-pod-name}* name.

=== Check the application

Just like we did before, hit the following URLs, using a utility like `curl`:


.Send and consume messages using a queue:
[source,bash]
----
$ curl -X GET http://localhost:8080/hello/message/send?content=Hello%20World
Sent Hello World to getting-started-queue
----

== What's next?

link:simple-microservice-jms-part2[{simple-microservice-jms-part2}]

[[references]]
== References

* Source code for this post: {source-code-git-repository}/tree/simple-microservice-jms-part21
* link:https://github.com/wildfly-extras/wildfly-datasources-galleon-pack[wildfly-datasources-galleon-pack]
* link:https://github.com/wildfly/wildfly-s2i/blob/main/examples/postgresql[PostgreSQL datasource example]

Back to Guides

< link:../get-started-microservices-on-kubernetes[Back to Getting Started with WildFly micro-services on Kubernetes]