---
layout: post
title:  "WildFly 8.2 Final is released!"
date:   2014-11-20 22:35:00 -0600
tags:   announcement, release
author: jgreene
---

= WildFly 8.2 Final is released!

I'm happy to announce the release of link:{base_url}/downloads/[WildFly 8.2.0.Final]! This release 
includes a number of improvements and bug fixes over the last release, 8.1.0.Final. 

CDI 1.2 & Weld 2.2
------------------
WildFly 8.2 builds upon the existing Java EE7 support, by adding the latest iteration of CDI,
which includes improved discovery semantics and better compatibility with AtInject (JSR 330)
implementations.

Additionally, Weld, our CDI implementation has been updated with improved performance. Large deployments
were observed to be as much as *20% faster* to deploy. 

For more details, see the Weld 2.2 link:http://weld.cdi-spec.org/news/2014/04/15/weld-220-final[release announcement].

Web Sockets 1.1 (JSR-356)
-------------------------
Undertow now supports the new Web Sockets 1.1 APIs, which allows Java 8 lambdas to be used as message handlers. Additionally
the TCK for 1.1 is much more extensive, with nearly three times the tests. This ultimately leads to better portability and 
quality of conformant implementations, such as WildFly.

Other Improvements
------------------
* New mechanism to load tag libraries from module
* EJBs in WARs now inherit the WAR security domain
* SSO session id cookie name is now configurable
* Notification support added to the domain management API
* Improved JASPI Support for Web Services
* HTTPSession sharing can be configured between WARs in the same EAR
* Reverse proxy configuration now uses outbound-socket-binding
* Custom http handlers now configurable in standalone.xml/domain.xml
* More Web Service management attributes are hot changeable
* A number of usability improvements to the Web Console
* TLS Cipher suites are now configurable in security realms

Issue Resolution
----------------
* 107 issues were resolved since 8.1

Component Updates
-----------------
* Jackson 2.4.1
* Mojarra 2.2.8-jbossorg-1
* Undertow 1.1.0.Final
* JSoup 1.7.1
* Apache CXF 2.7.13
* Apache Santuario 1.5.7
* Apache WS Security 1.6.17
* EL 3.0.1-b05
* Hibernate 4.3.7.Final
* Hibernate Validator 5.1.3.Final
* HornetQ 2.4.5.Final
* HAL 2.4.9.Final
* IronJacamar 1.1.9.Final
* Jandex 1.2.1.Final
* JBoss Marshalling 1.4.9.Final
* JBoss Remoting 4.0.6.Final
* RestEASY 3.0.10.Final
* JSTL 1.1.2.Final
* Weld 2.2.6.Final
* JBoss WS CXF 4.3.2.Final
* XNIO 3.3.0.Final
* JGroups 3.4.5.Final
* PicketBox 4.0.21.Final
* PicketLink 2.6.0.Final
* JAXB 2.2.5.jboss-2
