---
layout: post
title:  "WildFly Swarm 1.0.0.Alpha3 Released!"
date:   2015-06-18 11:11:11 -0500
tags:   announcement release swarm
author: bobmcwhirter
---

= WildFly Swarm 1.0.0.Alpha3 Released!

Once again, we're delighted and enthralled to announce a release
of WildFly Swarm.  This time, it's *1.0.0.Alpha3*!

Since this follows quickly on the heels of the last release,
there's not a whole lot of major changes.  Rather, we've fixed
some things, enhanced others, written some tests, and generally
knocked it together a little sturdier.

== Changes

* Based on WildFly 9.0.0.CR2.
* You can now `stop()` the container.
* Better classloading for `javax.*` stuff.
* JPA improvements:
** Default datasources are now available.
** JPA is usable from within a normal WAR.
* WebSocket API included in the Undertow fraction.
* More configuration through the `wildfly-swarm-maven-plugin`.
* Serve static content (with or without a WAR/JAX-RS deployment).
* Magical `favicon.ico` support for JAX-RS deployments, mostly
  to avoid ugly stack-traces in the console.

== Documentation

We've started writing some documentation, which you can contribute to:

- link:http://wildfly.org/swarm/[http://wildfly.org/swarm/]

== Examples?

Yes indeed! We have a bunch of buildable and runnable examples at GitHub 
in one handy repository:

- link:https://github.com/wildfly-swarm/wildfly-swarm-examples[https://github.com/wildfly-swarm/wildfly-swarm-examples]

== What do I download?

There is no special download or installation instructions.  Simply start
using `org.wildfly.swarm` artifacts in your `pom.xml`, throw in the plugin
and continue doing your builds.  Everything should be available through Maven Central
shortly, and is in link:http://repository.jboss.org/nexus/[JBoss Nexus] now for the
impatient.

== Stay in Touch

You can keep up with the project through the link:https://www.hipchat.com/gSW9XYz69[WildFly HipChat]
room, link:http://twitter.com/wildflyswarm[@wildflyswarm on Twitter], or through
link:https://github.com/wildfly-swarm/wildfly-swarm/issues[GitHub Issues].
