---
layout: post
title:  "WildFly 11 CR1 is now available!"
date:   2017-08-25 23:00:00 -0600
tags:   announcement release
author: jgreene
---

= WildFly 11 CR1 is now available!

WildFly 11 CR1 is now available link:{base_url}/downloads[for download]! 

Since the Beta, 66 issues have been resolved. You can find the full list below. Provided that no major issues are found, we hope to release the final very soon.

The highlights of WildFly 11 are as follows:

Elytron - New Security Infrastructure
-------------------------------------
The biggest change in WildFly 11 is unification on a new common security framework across the full application server.  Previously we had two separate security infrastructures (picketbox and security-realms), each covering separate use cases, and largely operating independent of the other. In addition to unification, Elytron brings a number of advanced capabilities such as privilege propagation across multiple service invocations, identity switching, pre-request TLS verification, and rich security policies. Finally it improves the overall extensibility of the system allowing for tight integration with SSO / IDP systems such as KeyCloak. 

While WildFly 11 introduces a new security infrastructure, the existing security-domain and security-realm configurations and APIs are all present and internally mapped to Elytron. To further  ease the impact of this change, WildFly 11’s default configurations still use the legacy security-domains and security-realms. A subsequent release will convert the default configurations over to the new configuration model. 

For more information see the Elytron documentation:
https://docs.jboss.org/author/display/WFLY/WildFly+Elytron+Security

As well as the section on migration:
https://docs.jboss.org/author/display/WFLY/Migrate+Legacy+Security+to+Elytron+Security

Simplified EJB / Naming Proxies
-------------------------------
JNDI and EJB invocation have both been simplified and enhanced in WildFly 11. There is a new naming client library, WildFly Naming Client that allows you to easily configure access to WildFly with minimal properties and configuration. EJBs (and other resources) can be accessed in a dynamic discovery mode, or alternatively, in a new point to point mode that locks all EJB proxies to a specified address. This replaces the previous scoped context feature with more intuitive semantics that are ideal for ad-hoc behavior. Additionally, with the new Elytron authentication infrastructure, the user identity can now be changed in between requests. Finally, older clients from past WildFly releases can still be used with WildFly 11. 

See the following for more information on the new WildFly Naming client: +
https://github.com/wildfly/wildfly-naming-client

Request oriented EJB/JNDI over HTTP
-----------------------------------
Since WildFly 8, all protocols (with the exception of IIOP) can utilize HTTP Upgrade to communicate over a reduced set of ports on the server (one for management, and one for applications). However, since HTTP Upgrade converts the connection to the native protocol used, any HTTP load-balancers acting as an intermediary can only balance on initial connection establishment. To allow for balancing at the individual invocation level, a new “pure” HTTP protocol was added. Clients which utilize http:// URLs as opposed to remoting+http:// will obtain this new behavior. Since this protocol utilizes standard HTTP behavior, it can be efficiently balanced by any load-balancer, not just the one built into EAP.

WildFly OpenSSL & HTTP/2
------------------------

WildFly 11 now provides a JSSE provider that can offload TLS handling from the JVM’s internal implementation to an OpenSSL library on your system, typically improving TLS performance. If the version discovered and/or specified is 1.0.2 or greater, then WildFly will utilize OpenSSL’s ALPN support to provide HTTP/2 support. HTTP/2 support will be disabled on versions less than 1.0.2.

Note that HTTP/2 is also supported without OpenSSL, out of the box, on Java 8 (on VMs derived from OpenJDK) and Java 9 (using the new standard ALPN API). 

You can enable OpenSSL in the default configurations with the following CLI command:

[source]
----
/core-service=management/security-realm=ApplicationRealm/server-identity=ssl:write-attribute(name=protocol,value=openssl.TLS)
----

If your openssl library is not installed in a standard location, you will need to additionally set the +org.wildfly.openssl.path+ system property to point to the location of the library:

[source]
----
-Dorg.wildfly.openssl.path=/path/to/dir/with/openssl/lib
----

New Load-Balancer Configs
-------------------------
In order to simplify the setup of EAP as an HTTP load-balancer, there is an additional +standalone-load-balancer.xml+ configuration in the distribution, which is an instance slimmed to just running the load balancing services. Additionally the stock +domain.xml+ also includes this as a profile configuration that can be referenced by server groups. 

Graceful Shutdown/Startup Improvements
--------------------------------------
Distributed transactions are now handled by the graceful shutdown mechanism. Existing transactions will allow local operations to continue, but any new in-flowed transaction will be rejected. Additionally there is a new EJB parameter that allows for additional remote calls to occur against an established/active remote transaction. Finally you can now start the server directly in suspended mode, for staging changes. This is now part of the default start sequence where the server enters suspend first, and then resumes after all services have launched, so new requests aren’t accepted during the brief window of the server starting.


Web Console Improvements
-------------------------
A number of Web Console improvements are included in WildFly 11, including the ability to see recent configuration changes, to manage active JMS transactions, manage active batch jobs, manage Undertow filters, and test data-sources during creation.  

Management and Configuration Improvements
-----------------------------------------
WildFly 11 now supports remote managed exploded deployments, which allows remote management clients the ability to update content within the deployment, such as html and jsp files without requiring a full redeployment. Additionally there is a new management operation that can be used to read individual files in any deployment. In addition to these new capabilities, errors in the XML now lead to pretty printed easier to understand error messages,

Also notable is that CLI tab completion can now tab complete attribute reference values that have capabilities present, such as references to socket bindings.  Finally, there is a new SPI for server extensions, that can be used to register a process state listener, and react to server life-cycle changes (such as the server stopping).

Jira Release Notes
------------------
The full list of issues resolved is available link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12313721&version=12328764[here].
