---
layout: post
title:  "Announcing public CI"
date:   2017-05-05 8:00:00 +0100
tags:   announcement continuous-integration
author: jgreene
description: "WildFly public CI"
---

= Announcing public CI

We are proud to announce our https://ci.wildfly.org/[public CI] system, which is running integration tests for WildFly, WildFly Core, Undertow, and many other related projects.
This system ensures that we do not merge anything that is broken and that our master is always stable.


CI also helps us with testing pull requests by:

* Making sure the code works on most common target platforms, currently Linux and Windows.
* Integration testing components as part of the full WildFly test suite. This is most often used when testing WildFly Core, where we test core itself as well as changes to core integrated on top of WildFly. This ensures that the latest core always works with the latest WildFly master.
* Running additional test suites such as mixed-domain tests, which are a bit harder to set up and run locally.
* Running complex integration tests that span across multiple projects, such as Elytron integration work that is landing in WildFly 11.

It is also utilized to test WildFly against various platforms and JDK combinations, such as testing the IBM JDK on Linux and Windows, testing Solaris SPARC, as well as regularly testing early builds of JDK 9.
CI also produces nightly builds of WildFly and WildFly core, which you can follow on https://developer.jboss.org/thread/224262[our forums].

We are using TeamCity as our CI with a few of our own customizations, including the following:

* A bit-modified, unofficial https://github.com/ctomc/TeamCity.GitHub[TeamCity.GitHub plugin] that allows us to post failed tests and other details of the failure to the pull request.
* A https://github.com/ctomc/pull-player/[pull-player], which we use as our trigger for pull requests. It provides us with a whitelisting of pull request authors for which CI tests are auto-triggered to prevent denial-of-service attacks. It also provides an option to retrigger CI testing by adding the comment “retest this please” to the pull request.

The system is powered by three servers running an ESXi hypervisor with everything else virtualized.

The front entry point is running Nginx with configured HTTP that is using an SSL certificate provided by https://letsencrypt.org/[Let’s Encrypt].

The infrastructure is managed by https://github.com/ansible/ansible[Ansible] with a set of our https://github.com/ctomc/ansible-playbooks/tree/master/teamcity-agent[playbooks].

We would like to *thank JetBrains*, which kindly donated the open source license for TeamCity.
