---
layout: post
title:  "New WildFly 22 Beta1 and 21.0.2 releases"
date:   2020-12-17
tags:   announcement release
author: bstansberry
description: WildFly 22 Beta1 and 21.0.2.Final are now available for download.
---

= WildFly 22 Beta and 21.0.2.Final

== Year End Treats

I'm pleased to announce that two new WildFly releases are available for download at https://wildfly.org/downloads.

First you can get WildFly 22.0.0.Beta1 and have a look at what's coming soon in WildFly 22.  This also includes an update of WildFly Preview.

Release notes for that release are link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12352283[here], with issues fixed in the underlying WildFly Core betas listed link:https://issues.redhat.com/secure/ConfigureReport.jspa?versions=12352615&versions=12352272&versions=12351519&versions=12346847&sections=all&style=none&selectedProjectId=12315422&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin%3Areleasenotes&Next=Next[here].

For developers using our bootable jar feature, please have a look at the new dev-watch mode that Jean-Francois Denise describes in link:https://www.wildfly.org/news/2020/12/15/bootable-jar-3.0.Beta-Released/[his latest blog post].

We've also done a micro update of WildFly 21, a new WildFly 21.0.2.Final release. This includes a fix for CVE-2020-27822, a medium impact CVE.

Release notes for that release are link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12352600[here]. Thank you to Rafael Paz and Michel Erard for reporting the problems that led to these fixes! 

Thank you to everyone in the WildFly community for your support of WildFly in 2020. It's been a trying year but I'm excited by and proud of the progress we've made. I wish all of you and your families a happy and healthy rest of the year, and I'm looking forward to a great 2021!

Best regards,

Brian
