---
layout: post
date:   2020-01-17 08:00:00 -0600
tags:   announcement, release
author: bstansberry
description: WildFly 19.0.0.Beta3 with Eclipse MicroProfile 3.3 Support
---

= WildFly 19.0.0.Beta3 with Eclipse MicroProfile 3.3 Support

I'm pleased to announce that with today's WildFly 19.0.0.Beta3 release WildFly supports the link:https://download.eclipse.org/microprofile/microprofile-3.3/microprofile-spec-3.3.html[Eclipse MicroProfile 3.3 platform specifications]! The WildFly 19 Beta3 zip is now available link:{base_url}/downloads[for download].

With the January release of WildFly 19 Beta1 we link:{base_url}/news/2020/01/17/WildFly19-Beta-Released[added support for MicroProfile 3.2]. Since the MicroProfile 3.3 release was coming in February and the delta from 3.2 wasn't _too_ extreme we decided to go ahead and delay WildFly 19 a bit and go for MicroProfile 3.3 support. Thanks to some heroic efforts from the WildFly developers and testers and a huge assist from the link:https://smallrye.io/[Smallrye community] we've been able to get this done. Thank you all, and congratulations on this achievement!

WildFly now provides support for the following MicroProfile specifications:

[cols=",",options="header"]
|===
|Specification |Version in WildFly 19
|MicroProfile Config | 1.4
|MicroProfile Fault Tolerance | 2.1
|MicroProfile Health Check | 2.2
|MicroProfile JWT Authentication | 1.1
|MicroProfile Metrics | 2.3
|MicroProfile OpenAPI | 1.1
|MicroProfile OpenTracing | 1.3
|MicroProfile Rest Client | 1.4
|===

We also provide all of the MicroProfile specs that are also part of EE 8.

As I noted in my post about the 19.0.0.Beta1 release, WildFly 19 includes three new subsystems to provide the MicroProfile specs that weren't in WildFly 18: `microprofile-fault-tolerance-smallrye`, `microprofile-jwt-smallrye` and `microprofile-openapi-smallrye`.

We've also added two new standard configuration files to help guide users toward server configurations well suited for microservice use cases:

* `standalone-microprofile.xml`
** Provides our MicroProfile platform implementations combined with JAX-RS and technologies JAX-RS applications commonly use to integrate with external services.
* `standalone-microprofile-ha.xml`
** Similar to `standalone-microprofile.xml` but with support for high availability web sessions and distributed Hibernate second-level caching.

Our other standard config files (e.g. `standalone.xml`) also include the subsystems needed to support Config, JWT, Health, Metrics, OpenTracing and Rest Client. The inclusion of JWT is new with the Beta 3 release.

On to Final!
------------

We plan to have a pretty short bake period for this beta during which we'll get a couple more bug fixes in and then we're shooting for the WildFly 19 Final release in 5 to 10 days.


Enjoy, please link:https://groups.google.com/forum/#!forum/wildfly[give us feedback], and as always, thank you so much for your support of WildFly!
