---
layout: post
title:  "WildFly 23 S2I images have been released on quay.io"
date:   2021-03-18
tags:   wildfly galleon
author: jfdenise
---

= WildFly 23 S2I images have been released on quay.io

==  WildFly 23 S2I Docker images

The WildFly S2I (Source-to-Image) builder and runtime Docker images for WildFly 23 have been released on link:https://quay.io/organization/wildfly[quay.io/wildfly].
 
For a complete documentation on how to use these images using S2I, OpenShift and Docker, 
refer to the WildFly S2I link:https://github.com/wildfly/wildfly-s2i/blob/wf-23.0/README.md[README].

== Adding the imagestreams and template to OpenShift

At some point the new images will be made available from the OpenShift catalog and image repository. But you can already use these images by adding them yourselves to your OpenShift cluster.

* WildFly S2I builder image stream:
```
oc create -n myproject -f https://raw.githubusercontent.com/wildfly/wildfly-s2i/wf-23.0/imagestreams/wildfly-centos7.json
```
* WildFly runtime image stream: 
```
oc create -n myproject -f https://raw.githubusercontent.com/wildfly/wildfly-s2i/wf-23.0/imagestreams/wildfly-runtime-centos7.json
```
* Chained build template: 
```
oc create -n myproject -f https://raw.githubusercontent.com/wildfly/wildfly-s2i/wf-23.0/templates/wildfly-s2i-chained-build-template.yml
```

NB: If you import the image streams into your project, be sure to set the _ImageStreams Namespace_ (`IMAGE_STREAM_NAMESPACE` argument) to your project namespace in the template. _openshift_ being the default namespace.

Enjoy!
