---
layout: post
title:  "WildFly 23 is released!"
date:   2021-03-11
tags:   announcement release microprofile jakartaee
author: bstansberry
description: WildFly 23.0.0.Final is now available for download
---

= WildFly 23 is released!

I'm pleased to announce that the WildFly 23 Final zip is now available link:https://wildfly.org/downloads[for download].

It's been a busy time since the January WildFly 22 release, with a bit shorter development cycle than normal. But a lot has been accomplished. Let's have a look at what's new.

== New Features

=== MicroProfile 4.0

In this release we have moved our MicroProfile platform implementations from the 3.3 platform specification versions to the 4.0 versions. WildFly 23 supports the following MicroProfile platform specifications:

[cols=",",options="header"]
|===
|Specification |Version in WildFly 23
|MicroProfile Config | link:https://github.com/eclipse/microprofile-config/releases/tag/2.0[2.0]
|MicroProfile Fault Tolerance | link:https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/3.0[3.0]
|MicroProfile Health | link:https://github.com/eclipse/microprofile-health/releases/tag/3.0[3.0]
|MicroProfile JWT Authentication | link:https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.2[1.2]
|MicroProfile Metrics | link:https://github.com/eclipse/microprofile-metrics/releases/tag/3.0[3.0]
|MicroProfile OpenAPI | link:https://github.com/eclipse/microprofile-open-api/releases/tag/2.0[2.0]
|MicroProfile OpenTracing | link:https://github.com/eclipse/microprofile-opentracing/releases/tag/2.0[2.0]
|MicroProfile Rest Client | link:https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0[2.0]
|===

We also provide all of the MicroProfile specs that are also part of Jakarta EE 8.

Please note that an link:https://download.eclipse.org/microprofile/microprofile-4.0/microprofile-spec-4.0.html#_compatibility_disclaimer[overarching goal of MicroProfile is to prioritize innovation over legacy compatibility]. This may result in incompatible changes between specification releases, which WildFly will necessarily reflect. With MicroProfile 4.0 the following specifications include API incompatible changes:

* link:https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_incompatible_changes[Config]
* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0/microprofile-fault-tolerance-spec-3.0.html#_backward_incompatible_changes[Fault Tolerance]
* link:https://download.eclipse.org/microprofile/microprofile-health-3.0/microprofile-health-spec-3.0.html#_incompatible_changes[Health]
* link:https://download.eclipse.org/microprofile/microprofile-metrics-3.0/microprofile-metrics-spec-3.0.html#_breaking_changes[Metrics]
* link:https://download.eclipse.org/microprofile/microprofile-open-api-2.0/microprofile-openapi-spec-2.0.html#_incompatible_changes[Open API]

=== MicroProfile Reactive Messaging

WildFly 23 now provides link:https://github.com/wildfly/wildfly-proposals/blob/master/microprofile/WFLY-13640_MicroProfile_Reactive_Messaging.adoc[Tech Preview support for MicroProfile Reactive Messaging]. This includes providing a connector for interaction with Kafka streams.

This capability adds support for two more MicroProfile specifications to WildFly, implemented via two new extensions and subsystems:

[cols=",",options="header"]
|===
|Specification |Version in WildFly 23
|MicroProfile Reactive Messaging | link:https://github.com/eclipse/microprofile-reactive-messaging/releases/tag/1.0[1.0] 
|MicroProfile Reactive Streams Operators | link:https://github.com/eclipse/microprofile-reactive-streams-operators/releases/tag/1.0.1[1.0.1]
|===

Please note that these extensions and subsystems are not included by default in the standard standalone.xml files that WildFly provides. Users who want them can add them to their configuration by using Galleon to link:https://docs.wildfly.org/23/Galleon_Guide.html[provision a server] or link:https://docs.wildfly.org/23/Bootable_Guide.html[build a bootable jar] and telling Galleon to include the new Galleon layers we've added for these. Or, use our zip and use the CLI to add the new extensions and subsystems. Further details can be link:https://docs.wildfly.org/23/Admin_Guide.html#MicroProfile_Reactive_Streams_Operators_SmallRye[found in the WildFly Admin Guide].

=== Expression Resolution from a Credential Store

WildFly 23 adds support for expressions in the management model to be link:https://github.com/wildfly/wildfly-proposals/blob/master/elytron/WFCORE-4360-CredentialStore_Expression_Resolution.adoc[encrypted using AES encryption and dynamically decrypted at runtime using a `SecretKey` from a credential store].

This enhancement makes use of a new resource `expression-encryption` in the `elytron` subsystem to configure the expression resolution. This new resource also
contains a management operation `create-expression` which allows users to create encrypted expressions using the usual management clients.

In addition to the new resource for expression resolution a new `secret-key-credential-store` has been added for the purpose of providing an initial secret key to the application server process. In the past users needed to rely on masking a password but this was achieved using a well known public password and password based encryption.  Starting from a secret key allows administrators to manage their own initial secret.  Both this new credential store resource and the existing `credential-store` resource have been updated to support the generation of secret keys as well as the ability to export and import previously generated secret keys.

Finally the `wildfly-elytron-tool` has also been updated to support both types of credential store and the `credential-store` command updated to support
management of secret keys and the generation of encrypted tokens for use in expressions.

Users of the deprecated Picketbox-vault-backed expression resolution mechanism are strongly encouraged to move to this new feature, as our intent is to remove support for Picketbox and the Picketbox-vault in an upcoming release.

=== Provisioning and Managing WildFly

* For users who wish to deploy multiple applications on the same server instance where one application during startup needs to make an external (i.e. over the network) invocation on another, we have provided a mechanism link:https://github.com/wildfly/wildfly-proposals/blob/master/server/WFCORE-4291_restore_legacy_not_graceful_startup_mode.adoc[to turn off the default 'graceful startup' behavior] that prevents such requests being accepted. Not handling such requests can prevent startup of the deployment making them and prevent the server booting. A number of users have asked for this use case tp be supported, so we have done so, but this is not a recommended deployment architecture. A server that is not booting gracefully may receive incoming requests that it is not yet ready to handle, resulting in errors.
* There is now link:https://github.com/wildfly/wildfly-proposals/blob/master/scripts/WFCORE-5261-common-conf.adoc[support for common script configurations]. A common file can be used to set up the environment for all the shell scripts that WildFly provides. For example, you can set the JAVA_HOME in a common.conf script configuration file to ensure the same version of Java is used for all scripts.
* When launching a WildFly bootable jar, users can link:https://github.com/wildfly/wildfly-proposals/blob/master/bootable-jar/WFCORE_5324_CLI_script_exec_runtime.adoc[instruct the bootable jar to execute an external CLI script] as part of boot. This provides a mechanism for performing final configuration that cannot be accomplished via the preferred approach of configuring at build time or via typical runtime customization mechanisms like setting environment variables or system properties. This support is Tech Preview as the mechanism may change in later releases.

=== Messaging

* The management API can now be used to link:https://github.com/wildfly/wildfly-proposals/blob/master/messaging/WFLY-6660_artemis_data_tools.adoc[get a dump of the embedded Artemis broker's journal] for investigative purposes.
* The behavior of the embedded Artemis broker's critical-analyzer feature link:https://github.com/wildfly/wildfly-proposals/blob/master/messaging/WFLY-13959_critical_analyzer.adoc[can now be configured].
* The embedded Artemis broker can be configured to link:https://github.com/wildfly/wildfly-proposals/blob/master/messaging/WFLY-13991_keep_corrupted_journal_files.adoc[retain a corrupted journal file] for subsequent investigation instead of immediately deleting it.
* A `call-timeout` attribute has been link:https://github.com/wildfly/wildfly-proposals/blob/master/messaging/WFLY-14133_configurable_bridge_call_timeout.adoc[added to the Jakarta Messaging core bridge configuration]. The attribute specifies the time out for blocking calls performed by a core bridge.

=== Other areas

* The Jakarta Concurrency managed executors provided by the `ee` subsystem can be link:https://github.com/wildfly/wildfly-proposals/blob/master/concurrency/WFLY-12896_EE_Concurrency_Hung_Tasks_Termination.adoc[configured to detect and automatically terminate tasks] that have been executing for an unexpectedly long time. Such tasks can also be manually terminated.
* The `transaction` subsystem now supports link:https://github.com/wildfly/wildfly-proposals/blob/master/transaction/WFLY-10009_EAP7-981_Introduce_Maximum_Timeout.adoc[configuring a maximum timeout] for transactions.
* The `undertow` subsystem can now be link:https://github.com/wildfly/wildfly-proposals/blob/master/undertow/WFLY-12473_obfuscate-session-route.adoc[configured to obfuscate the server instance-id data] included as part of the request and response `JSESSION_ID` cookie. 
* Deployments can now depend on and use the APIs provided by the following Infinispan-related modules without getting a private API usage warning:
** `org.infinispan` (embedded cache)
** `org.infinispan.client.hotrod` (client for remote infinispan server)
** `org.infinispan.commons`
* Principal propagation of EJBs was different for legacy security and Elytron security in some cases. To provide a possibility to configure which behaviour should apply, we link:https://github.com/wildfly/wildfly-proposals/blob/master/elytron/WFLY-14074-normalization-of-principal-propagation.adoc[added a new attribute] `legacy-compliant-principal-propagation` to `application-security-domain` component in the `ejb3` subsystem. This attribute is optional and the principal propagation is legacy compliant by default.

== WildFly Preview

As I link:https://www.wildfly.org/news/2020/11/12/Jakarta-EE-9-with-WildFly-Preview/[announced in November] when we released WildFly 22 Alpha1, along with our traditional Jakarta EE 8 distribution we want to give our users a preview of what will be coming in WildFly as we move on to EE 9 and later. We call this distribution "WildFly Preview". The WildFly 23.0.0.Final release includes an update to WildFly Preview. _Even though this is coming from a .Final tag of the WildFly codebase, WildFly Preview should always be regarded as a tech-preview/beta distribution._

EE 9 is primarily about implementing the necessary change in the Jakarta EE APIs from the javax.* package namespace to the jakarta.* namespace. This is a big change that is going to take a while to percolate through the EE ecosystem, e.g. for the many projects that compile against the EE APIs to provide versions that use jakarta.*. While this happens we want to continue to deliver new features and fixes to our community, so the primary WildFly distribution will continue to provide the EE 8 APIs.

== Feature Pack Changes

WildFly users can use Galleon feature packs to link:https://docs.wildfly.org/23/Galleon_Guide.html[provision a server] or link:https://docs.wildfly.org/23/Bootable_Guide.html[build a bootable jar]. The WildFly project produces five different feature packs: `wildfly-core`, `wildfly-servlet`, `wildfly-ee`, `wildfly` and `wildfly-preview`. The composition of these feature packs has changed somewhat in WildFly 23, in that the `wildfly-ee` feature pack no longer _depends on_ `wildfly-servlet` or (transitively) `wildfly-core`. Instead it directly incorporates the same content that was previously made available via a dependency relationship. For most users, this subtle difference should have no impact. However, there are some cases where it might:

* If you are producing your own feature pack that depends on `wildfly` or `wildfly-ee` you may need to adjust your pom.xml and wildfly-feature-pack-build.xml to remove any dependency on wildfly-servlet and wildfly-core. 
* If your build uses another feature pack that depends on the `wildfly` or `wildfly-ee` feature packs, you should wait to upgrade to WildFly 23 until a release of that feature pack that depends on the WildFly 23 packs is available. A commonly used example of this is the link:https://github.com/wildfly-extras/wildfly-datasources-galleon-pack[`org.wildfly:wildfly-datasources-galleon-pack`] feature pack. Users of that feature pack should move to the 1.2.3.Final release that came out today. 

The WildFly project still produces the `wildfly-core` and `wildfly-servlet` feature packs for those who wish to use them, although they may be discontinued at some point.


== Standards Support

WildFly 23.0.0 is a Jakarta EE 8 compatible implementation, with both the Full Platform and the Web Profile. Evidence supporting our certification is available link:https://github.com/wildfly/certifications/blob/EE8/WildFly_23.0.0.Final/jakarta-full-platform.adoc#tck-results[for the Full Platform] and link:https://github.com/wildfly/certifications/blob/EE8/WildFly_23.0.0.Final/jakarta-web-profile.adoc#tck-results[for the Web Profile].

Beginning with WildFly 23 we will be exclusively focusing on the Jakarta EE test suite for EE certification / compliance.

WildFly 23 is also a compliant implementation of the MicroProfile 4.0 platform specification.

The WildFly Preview distribution released today is not yet a compatible implementation of Jakarta EE 9 or MicroProfile 4.0. We're continuing to make good progress toward being able to certify compatibility, but we're not there yet. The main area where users may hit meaningful issues related to EE compliance is in webservices if deployment descriptors using the EE 9 xml schemas are used. This can be worked around by using EE 8 schemas, which are functionally equivalent.

== JDK Support

Our recommendation is that you run WildFly on the most recent long-term support JDK release, i.e. on JDK 11 for WildFly 23. While we do do some testing of WildFly on JDK 12 and 13, we do considerably more testing of WildFly itself on the LTS JDKs, and we make no attempt to ensure the projects producing the various libraries we integrate are testing their libraries on anything other than JDK 8 or 11.

WildFly 23 also is heavily tested and runs well on Java 8. We plan to continue to support Java 8 at least through WildFly 24, and probably beyond.

While we recommend using an LTS JDK release, I do believe WildFly runs well on JDK 13. By run well, I mean the main WildFly testsuite runs with no more than a few failures in areas not expected to be commonly used. We want developers who are trying to evaluate what a newer JVM means for their applications to be able to look to WildFly as a useful development platform. We do see a couple of test failures with JDK 13 when using the deprecated Picketlink subsystem and WS Trust.

Work to allow WildFly to run on JDK 15 and later is ongoing. We're continuing our work to digest fully some of the package removals that came in JDK 14, particularly in the security area. The biggest barrier we face is the deprecated legacy security implementation based on Picketbox cannot support JDK 14. We intend to remove support for that security implementation quite soon and to only provide Elytron-based security.

Please note that WildFly runs on Java 11 and later in classpath mode.

== Documentation

The WildFly 23 documentation is available at the link:https://docs.wildfly.org/23/[docs.wildfly.org site]. The WildFly 23 management API documentation is in the link:https://docs.wildfly.org/23/wildscribe[wildscribe section of the WildFly 23 docs].

== Jira Release Notes

The full list of issues resolved is available link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12354095[in the WFLY JIRA project]. Issues resolved in the WildFly Core 15 release included with WildFly 23 are available link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12315422&version=12354044[in the WFCORE JIRA project].

== Enjoy!

Thank you for your continued support of WildFly.  We'd love to hear your feedback at the link:https://groups.google.com/forum/#!forum/wildfly[WildFly forum]. 
