---
layout: post
title:  "WildFly 23.0.2 is released!"
date:   2021-04-29
tags:   announcement release
author: darranl
description: WildFly 23.0.2.Final is now available for download.
---

= WildFly 23.0.2 is released!

WildFly 23.0.2.Final is now available link:https://wildfly.org/downloads[for download].

After the release of Jakarta EE 9 the Jakarta EE Platform Project has been busy with the link:https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9.1ReleasePlan[Jakarta EE 9.1 Release].  This has now progressed to the point that a candidate release of the Jakarta EE 9.1 TCK is available with WildFly 23.0.2.Final being our release candidate as a compatible implementation based on this TCK.

== WildFly Preview and Jakarta EE 9

The link:https://docs.wildfly.org/23/WildFly_and_WildFly_Preview.html[WildFly Preview variant] of the server still passes the Jakarta EE 9 for the TCKs link:https://github.com/wildfly/certifications/blob/EE9/WildFly_23.0.2.Final/jakarta-full-platform.adoc[Full Platform] and the link:https://github.com/wildfly/certifications/blob/EE9/WildFly_23.0.2.Final/jakarta-web-profile.adoc[Web Profile].  We have previously sent a link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/326[compatibility certification request for the Full Platform] for WildFly Preview 23.0.1.Final and a link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/315[compatibility certification request for the Web Profile] for WildFly Preview 23.0.0.Final.

Once released, Jakarta EE 9.1 will be the first Jakarta EE release that allows a server to certify using both Java 8 and Java 11 for both the web profile and the full platform.

For the various permutations we have published the following test results using the link:https://docs.wildfly.org/23/WildFly_and_WildFly_Preview.html[WildFly Preview variant] of the server with the candidate release of the Jakarta EE 9.1 TCKs and submitted corresponding certification requests to Eclipse.

 * link:https://github.com/wildfly/certifications/blob/EE9.1/WildFly_23.0.2.Final/jakarta-web-profile-jdk8.adoc[Test Results - Web Profile - Java 8] / link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/349[Certification Request - Web Profile - Java 8]
 * link:https://github.com/wildfly/certifications/blob/EE9.1/WildFly_23.0.2.Final/jakarta-web-profile.adoc[Test Results - Web Profile - Java 11] / link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/347[Certification Request - Web Profile - Java 11]
 * link:https://github.com/wildfly/certifications/blob/EE9.1/WildFly_23.0.2.Final/jakarta-full-platform-jdk8.adoc[Test Results - Full Platform - Java 8] / link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/348[Certification Request - Full Platform - Java 8]
 * link:https://github.com/wildfly/certifications/blob/EE9.1/WildFly_23.0.2.Final/jakarta-full-platform.adoc[Test Results - Full Platform - Java 11] / link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/346[Certification Request - Full Platform - Java 11]

We are hopeful this will mean the link:https://docs.wildfly.org/23/WildFly_and_WildFly_Preview.html[WildFly Preview variant] of the server can be declared compatible with Jakarta EE 9.1 at the time it is released for the Web Profile and Full Platform against both Java 8 and Java 11.

This has been a busy couple of weeks working through the remaining issues to pass the candidate release of the Jakarta EE Platform 9.1 TCKs with particular thanks to Brian Stansberry, Scott Marlow, Richard Opalka, Jean-Francois Denise, Tomasz Adamski, Jim Ma, and Alessio Soldano for making it happen.

As is described in the link:https://docs.wildfly.org/23/WildFly_and_WildFly_Preview.html[WildFly docs], WildFly Preview is a tech preview variant of the server meant to allow our community to get an early look at new things we're looking to eventually bring into the standard WildFly variant. Currently, the main (but not only) difference from standard WildFly is support of Jakarta EE 9 and 9.1 instead of EE 8.

WildFly Preview is not a compatible Jakarta EE 8 or MicroProfile Platform 4.0 implementation, although we do expect most apps using the EE 8 and MP 4 APIs to run well on it.

WildFly Preview is available on the link:https://wildfly.org/downloads[download page], next to the standard WildFly download links for the same version. Look for the 'WildFly Preview EE 9 Distribution' links.

== Release Notes

The full list of issues resolved in WildFly 23.0.2 is available link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12356561[here]. WildFly 23.0.2.Final is using the same version of WildFly Core as was used in the 23.0.1.Final release so no WildFly Core specific fixes have been applied.


Enjoy!
