---
layout: post
title:  "Jakarta EE 10 is released and WildFly is compatible!"
date:   2022-09-22
tags:   announcement release compatibility
author: bstansberry
description: WildFly 27.0.0.Alpha5 is a compatible implementation of Jakarta EE 10
---

= Jakarta EE 10 is released; WildFly is compatible!

Congratulations to everyone involved with Jakarta EE for today's announced link:https://twitter.com/JakartaEE/status/1572906807320018945[general availability of Jakarta EE 10]! It's great to see continued advances in Jakarta EE, particularly link:https://jakarta.ee/specifications/cdi/4.0/[Jakarta Contexts and Dependency Injection 4.0] with the new link:https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#_cdi_lite[CDI Lite], along with the new link:https://jakarta.ee/specifications/coreprofile/10/[Jakarta EE 10 Core Profile].

I'm particularly happy to announce that our hard work in the WildFly community on EE 10 is paying off. Last week we released link:https://www.wildfly.org/downloads/[WildFly 27.0.0.Alpha5], and this week compatibility certification requests for EE 10 link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/539[Full Platform] and link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/540[Web Profile] were accepted at Jakarta. WildFly Preview has also been a compatible implementation of the EE 10 Core Profile since the 27.0.0.Alpha1 release.  It's great to see so many links to WildFly on the link:https://jakarta.ee/compatibility/download/[Jakarta EE download page].

All of these certifications were for running on either Java SE 11 or Java SE 17. 

Compatibility Certification Information for 27.0.0.Alpha5 is available from the WildFly certifications GitHub repo:

* link:https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-full-platform-jdk11.adoc#tck-results[EE 10 Full Platform -- SE 11]
* link:https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-full-platform-jdk17.adoc#tck-results[EE 10 Full Platform -- SE 17]
* link:https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-web-profile-jdk11.adoc#tck-results[EE 10 Web Profile -- SE 11]
* link:https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-web-profile-jdk17.adoc#tck-results[EE 10 Web Profile -- SE 17]

We'll be sending EE 10 Core Profile compatibility certification requests to Jakarta for standard WildFly 27.0.0.Alpha5 shortly. (As noted above, WildFly Preview has been compatible since 27.0.0.Alpha1.) Our TCK results that will back those certification requests are as follows:

* link:https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-core-jdk11.adoc#jakarta-core-profile-1000-tck-java-se-11-results[EE 10 Core Profile -- SE 11]
* link:https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-core-jdk17.adoc#jakarta-core-profile-1000-tck-java-se-17-results[EE 10 Core Profile -- SE 17]

Thank you to all the hard-working WildFly developers for your enormous efforts toward reaching this milestone. And thank you to our terrific user community for your support and feedback along the way.
 
A special word of thanks to Scott Stark, who led the EE 10 release at Jakarta, and to Scott Marlow who played a critical role there, particularly on the TCK. Way, way back in the day Scott Stark was the first person from JBoss I ever met, when I took a JBoss, Inc. training course that he taught. It's great to still be working with Scott almost twenty years later.

Congratulations as well to the Glassfish, Payara and Open Liberty developers all of whom have released compatible implementations of one or more of the EE 10 profiles. A big goal at Jakarta has been to create an environment where it's possible for multiple compatible implementations to be available on the day a new EE version becomes general available. It's great to see that effort continuing to bear fruit.

Looking forward, we're hard at work on completing WildFly 27. Keep an eye out for more release announcement related to that over the next few weeks.

Thank you for your continued support of WildFly. We’d love to hear from you at the link:https://groups.google.com/g/wildfly[WildFly forum].
