---
layout: post
title: 'New WildFly S2I and Runtime Multi-arch Images'
date: 2022-12-10
tags: wildfly galleon cloud wildfly-s2i openshift
description: This article provides details on the new S2I and runtime multi-arch images
author: jfdenise
---

This article provides details on the new S2I and runtime multi-arch images.

== New WildFly S2I and Runtime Multi-arch Images

These new multi-arch images (`linux/arm64` in addition to `linux/amd64`) have a different naming scheme than the current WildFly images 
to better handle multiple JDK versions and align with the tag scheme used for the WildFly centos7 docker images 
(as explained in https://www.wildfly.org/news/2022/11/10/wildfly-docker-temurin/[Updates on WildFly Docker Images] blog post).

NOTE: The previous WildFly images are now deprecated and are no longer updated.

The new multi-arch image names are:

* Runtime image: `quay.io/wildfly/wildfly-runtime:<tag>`
* S2I builder image: `quay.io/wildfly/wildfly-s2i:<tag>`

This change is described in this https://github.com/wildfly/wildfly-s2i/issues/408[Issue].

In short, the WildFly image names used to contain the JDK version (e.g: `wildfly/wildfly-s2i-jdk11`) leading to some lack of flexibility:

* An increasing number of new images for each new JDK version.
* No ability to identify a pair of images supporting the latest LTS (Long Term Support) JDK. 

The JDK version has been removed from the image name and moved to the image tag. In addition we have introduced a `latest` tag that 
identifies the images supporting the latest LTS JDK.

You can identify the exact images version supporting a given JDK version:

* `quay.io/wildfly/wildfly-runtime:1.0.0-jdk11` used to be `quay.io/wildfly/wildfly-runtime-jdk11:1.0.0`
* `quay.io/wildfly/wildfly-runtime:1.0.0-jdk17` used to be `quay.io/wildfly/wildfly-runtime-jdk17:1.0.0`
* `quay.io/wildfly/wildfly-s2i:1.0.0-jdk11` used to be `quay.io/wildfly/wildfly-s2i-jdk11:1.0.0`
* `quay.io/wildfly/wildfly-s2i:1.0.0-jdk17` used to be `quay.io/wildfly/wildfly-s2i-jdk17:1.0.0`

You can identify the latest images supporting a given JDK version:

* `quay.io/wildfly/wildfly-runtime:latest-jdk11` used to be `quay.io/wildfly/wildfly-runtime-jdk11:latest`
* `quay.io/wildfly/wildfly-runtime:latest-jdk17` used to be `quay.io/wildfly/wildfly-runtime-jdk17:latest`
* `quay.io/wildfly/wildfly-s2i:latest-jdk11` used to be `quay.io/wildfly/wildfly-s2i-jdk11:latest`
* `quay.io/wildfly/wildfly-s2i:latest-jdk17` used to be `quay.io/wildfly/wildfly-s2i-jdk17:latest`

You can now identify the latest image supporting the latest LTS JDK version (JDK 17 at the time of this writing):

* `quay.io/wildfly/wildfly-runtime:latest`
* `quay.io/wildfly/wildfly-s2i:latest`

NOTE: Relying on this image tag implies that the JDK version will get automatically updated when a new LTS JDK is 
released and supported by the WildFly images.

== Deprecated Snapshot Multi-arch Images

Up to now, we were releasing multi-arch images as preview ones in the `quay.io/wildfly-snapshots` organization:

* `quay.io/wildfly-snapshots/wildfly-runtime-jdk11-multi-arch:latest`
* `quay.io/wildfly-snapshots/wildfly-runtime-jdk17-multi-arch:latest`
* `quay.io/wildfly-snapshots/wildfly-s2i-jdk11-multi-arch:latest`
* `quay.io/wildfly-snapshots/wildfly-s2i-jdk17-multi-arch:latest`

These images are now deprecated and no longer updated.

== Deprecated WildFly Images

The following single-arch images are now deprecated and are no longer updated:

* `quay.io/wildfly/wildfly-runtime-jdk11:<tag>`
* `quay.io/wildfly/wildfly-runtime-jdk17:<tag>`
* `quay.io/wildfly/wildfly-s2i-jdk11:<tag>`
* `quay.io/wildfly/wildfly-s2i-jdk17:<tag>`

== New OpenShift Image Streams

The previous image streams (link:https://github.com/wildfly/wildfly-s2i/blob/main/imagestreams/wildfly-runtime-jdk11.yaml[wildfly-runtime-jdk11], 
link:https://github.com/wildfly/wildfly-s2i/blob/main/imagestreams/wildfly-runtime-jdk11.yaml[wildfly-runtime-jdk17], 
link:https://github.com/wildfly/wildfly-s2i/blob/main/imagestreams/wildfly-runtime-jdk11.yaml[wildfly-s2i-jdk11],
link:https://github.com/wildfly/wildfly-s2i/blob/main/imagestreams/wildfly-runtime-jdk11.yaml[wildfly-s2i-jdk17]) have been deprecated.

The new image streams are:

** WildFly s2i builder: link:https://raw.githubusercontent.com/wildfly/wildfly-s2i/main/imagestreams/wildfly-s2i.yaml[wildfl-s2i imagestream]
** WildFly runtime: link:https://raw.githubusercontent.com/wildfly/wildfly-s2i/main/imagestreams/wildfly-runtime.yaml[wildfly-runtime imagestream]

== Impact on Helm Charts for WildFly

link:https://github.com/wildfly/wildfly-charts[Helm Chart for WildFly] version `2.3.1` is required to use these new images.

Helm Chart for WildFly now uses the `quay.io/wildfly/wildfly-s2i:latest` and `quay.io/wildfly/wildfly-runtime:latest` (latest LTS JDK) 
by default, used to be JDK11.

If you have already installed the Helm Charts for WildFly, make sure to update your repository to the latest version. This is done by calling:

```
helm repo update
```

== Using the Images

The image naming change is transparent when using Helm Charts for WildFly. Usage of these images 
is covered by WildFly S2I link:https://github.com/wildfly/wildfly-s2i/tree/main/examples[examples], 
link:https://github.com/wildfly/wildfly-s2i/blob/main/README.md[README], 
wildfly-s2i image link:https://quay.io/repository/wildfly/wildfly-s2i[description] and wildfly-runtime image 
link:https://quay.io/repository/wildfly/wildfly-runtime[description]. 

== Summary

With the introduction of these new multi-arch images, we are putting in place a long term tagging scheme to better support future JDK versions.
You feedback as always is very welcome. Feel free to log these as new link:https://github.com/wildfly/wildfly-s2i/issues[project issues].

Thank-you!

JF Denise
