---
layout: post
title:  "WildFly Release Schedule"
date:   2023-05-11
tags:   announcement roadmap
author: bstansberry
description: WildFly's release pattern is going back to time-boxing
---

= WildFly Release Plans

As the WildFly project continues to move on from the major effort involved with integrating Jakarta EE 10, it's time to go back to the roughly time-boxed development and release model that worked so well from WildFly 12 until WildFly 26. During that period, the WildFly project followed a roughly time-boxed development model. Roughly every three months we produced a new WildFly major release, with a large set of features, enhancements and bug fixes. We didn't operate on a strict time schedule, but we tried to avoid significant schedule delays just to bring in particular feature or set of features. If a feature didn't make a particular release it could just go in the next one a few months later.

At the beginning of 2022, I link:https://www.wildfly.org/news/2022/01/21/WildFly-2022/[announced a temporary shift away from that development model] and toward a feature-boxed approach. We did this because it was a more effective way to implement the transition to EE 10. But with that work behind us, the consensus among the WildFly developers is that moving back to the old time-boxed apprach will allow more effective delivery of new features and fixes to our users.

Our aim is to produce feature releases in January, April, July and October. Experience has shown us that those months work best for not having development work overly disrupt summer or year end holidays.

We'll continue with our practice of releasing a Beta two weeks before the Final release, except for the January release, where the beta will be out somewhat earlier to avoid doing any release work in the latter part of December.

== 2023 - 2024 Release Schedule

The following is a rough schedule of when we intend to do feature releases over the remainder of 2023 and through 2024. Please note that these dates are subject to change.

|===
| Version |Beta Release |Final Release

|WildFly 29
|June 29, 2023
|July 13, 2023

|WildFly 30
|September 28, 2023
|October 12, 2023

|WildFly 31
|December 14, 2023 
|January 11, 2024 

|WildFly 32
|March 28, 2024
|April 11, 2024

|WildFly 33
|June 27, 2024
|July 11, 2024

|WildFly 34
|September 26, 2024
|October 10, 2024

|WildFly 35
|December 12, 2024
|January 9, 2024
|===

WildFly is only _roughly_ time boxed. We are certainly willing to delay a release to ensure adequate quality, and we would consider delaying a couple of weeks to include features of large enough significance. For example if a new MicroProfile release comes out in June and we need a bit more time to incorporate it in WildFly 29 we would consider delaying the WildFly 29 release somewhat. If we delayed a release we would not intend to then delay the next release; the next release would just have a shorter development window. The general idea though is to not block releasing waiting for features, as a quarterly cycle means a feature that misses a release can appear soon enough.

== Micro Releases

When we release each major we also create a new branch specific to that major. That branch is used to produce one micro (primarily bug fix) release for the major, with the micro usually released about a month after the major. This too is roughly time-boxed. Work on the WildFly 28.0.1 release, coordinated by Farah Juma, is currently in progress. The number of changes in the micro is typically small compared to what's gone into main in the same period, as we want to be particularly conservative about introducing bugs or behavior changes in the micro.  We've been consistently producing these micros since WildFly 17.0.1, and had done a few prior to that as well.

== Questions?

If you have questions or want to provide feedback, I encourage you to post on the link:https://groups.google.com/g/wildfly[WildFly forum], on the link:https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/[wildfly-dev mail list] or in link:https://wildfly.zulipchat.com/[Zulip chat]. I will be starting a thread on the forum about this topic.

Best regards,

Brian
