---
layout: post
title:  "New WildFly 36 Beta release"
date:   2025-03-27
tags:   announcement release
author: darranlß
description: WildFly 36 Beta is now available for download.
---

= WildFly 36 Beta is released!

I'm pleased to announce that the new WildFly 36.0.0.Beta1 release is available for download at https://wildfly.org/downloads.

As can be seen from the https://github.com/wildfly/wildfly/releases/tag/36.0.0.Beta1[Release Notes] a lot of issues were resolved in this release but I would also like to call out some of the following highlights:


* [https://issues.redhat.com/browse/WFLY-18582[WFLY-18582]] -- Add a prometheus endpoint to the micrometer extension
* [https://issues.redhat.com/browse/WFCORE-5718[WFCORE-5718]] -- Support remote+tls with EJBClient and remote-outbound-connection
* [https://issues.redhat.com/browse/WFLY-20476[WFLY-20476]] -- Promote ajp-listener AJP_ALLOWED_REQUEST_ATTRIBUTES_PATTERN to community stability
* [https://issues.redhat.com/browse/WFLY-20477[WFLY-20477]] -- Promote undertow subsystem's reuse-x-forwarded and rewrite-host header configurability to community stability

Within the WildFly Preview distribution we also https://issues.redhat.com/browse/WFLY-19397[upgraded to a beta of Hibernate ORM 7 and an alpha of Hibernate Search 8].

We've also enhanced https://docs.wildfly.org/wildfly-glow/[WildFly Glow], so it is now possible to https://github.com/wildfly/wildfly-proposals/issues/688[run a source-only WildFly application] using https://www.jbang.dev/[JBang]! 

Please try out this release and let us know how you get on.


