---
layout: post
date:   2020-01-17 08:00:00 -0600
tags:   announcement, release
author: bstansberry
description: MicroProfile 3.2 in WildFly 19.0.0.Beta1
---

= MicroProfile 3.2 in WildFly 19.0.0.Beta1

I'm pleased to announce that the WildFly 19 Beta1 zip is now available link:{base_url}/downloads[for download].

I typically don't blog about the WildFly betas, but I want to this time because I'm so thrilled to be able to say we've gotten implementations of all of the link:https://download.eclipse.org/microprofile/microprofile-3.2/microprofile-spec-3.2.html[MicroProfile 3.2 specifications] in this release!  This is the first WildFly release that includes all the MicroProfile platform specs.

We've added three new subsystems to provide support for the MicroProfile platform specs we've never supported before:

[cols=",,^",options="header"]
|===
|Specification |Version in WildFly 19|JIRA Issue
|MicroProfile Fault Tolerance | 2.0 | link:https://issues.redhat.com/browse/WFLY-12590[WFLY-12590]
|MicroProfile JWT Authentication | 1.1 | link:https://issues.redhat.com/browse/WFLY-12609[WFLY-12609]
|MicroProfile OpenAPI | 1.1 | link:https://issues.redhat.com/browse/WFLY-12313[WFLY-12313]
|===

MicroProfile 3.2 also includes updates to two of the specs we included in WildFly 18, so those have been updated as well:

[cols=",^,^",options="header"]
|===
|Specification |Version in WildFly 19|JIRA Issue
|MicroProfile Health Check | 2.1 | link:https://issues.redhat.com/browse/WFLY-12685[WFLY-12685]
|MicroProfile Metrics | 2.2 | link:https://issues.redhat.com/browse/WFLY-12686[WFLY-12686]
|===

As we did in WildFly 18, we also provide MicroProfile Config 1.3, OpenTracing 1.3, and Rest Client 1.3, the implementations of which have had some updates. In particular, the subsystem for integrating OpenTracing has been link:https://issues.redhat.com/browse/WFLY-12758[updated to provide a richer management API]. Finally, we of course provide all of the MicroProfile specs that are also part of Java EE 8.

WildFly's MicroProfile implementations are primarily based on the link:https://smallrye.io/[Smallrye] projects. (We use RESTEasy's Rest Client impl.) Many thanks to Ken Finnigan and all the folks in the Smallrye community for providing great implementations of these rapidly evolving specs!

It takes a *great* community to bring in major new features like this. A great number of other folks have helped; I thank you all and my apologies to anyone I've missed:

* Fabio Burzigotti
* Michael Edgar
* Paul Ferraro
* Emmanuel Hugonnet
* Radoslav Husar
* Jan Kasik
* Kabir Khan
* Darran Lofthouse
* Eduardo Martins
* Stefano Maestri
* Jeff Mesnil
* Miroslav Novak
* Ron Sigal
* Alessio Soldano
* Tobias Stadler
* Martin Stefanko
* Ivan Straka
* Rostislav Svoboda
* Sultan Zhantemirov

I'd particularly like to thank Stefano Maestri for his leadership in getting this done, and Michael Edgar and Tobias Stadler for providing a lot of the drive behind this -- and for putting up with our sometimes burdensome feature development processes!

Jira Release Notes
------------------
I'll wait for the WildFly 19 Final release to get into all the details, but 19.0.0.Beta1 includes a wide variety of other features, component updates, bugs fixes and enhancements beyond the MicroProfile work. The full list of issues resolved is available link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12340607[here]. This release incorporates WildFly Core 11.0.0.Beta7 -- see the link:https://issues.redhat.com/projects/WFCORE?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page&status=released[WildFly Core JIRA] for details of what was in the WildFly Core 11 betas.

Enjoy, and as always, thank you so much for your support of WildFly!
