---
layout: getstarted
title: Java Microservices on Kubernetes wih WildFly
---
:includedir: ./get-started-microservices-on-kubernetes/_includes
include::{includedir}/_titles.adoc[]
:page-liquid:

== Build simple WildFly Java Microservices and run them on link:https://kubernetes.io/[Kubernetes].

=== Intro

In this mini-serie, we will show how-to to quickly build some of the most common patterns in link:https://jakarta.ee/[Jakarta EE] (e.g. crating a JAX-RS service, connecting to an external Database, interacting with an external JMS Broker, etc.) and run them on link:https://kubernetes.io/[Kubernetes];

At some point, we'll go even further and show how-to build some common patterns in link:https://microprofile.io/[MicroProfile] (e.g. Rest Client to invoke a JAX-RS service in another application);

We will start by showing how-to build a link:https://docs.docker.com/[Docker Image] containing a WildFly Java Microservice (link:simple-microservice-part1[{simple-microservice-part1}]), and then we will run that link:https://docs.docker.com/[Docker Image] on link:https://kubernetes.io/[Kubernetes] (link:simple-microservice-part2[{simple-microservice-part2}]); this will set the basis to extend this example and implement the following patterns (link:simple-microservice-database-part1[{simple-microservice-database-part1}], etc.);

=== Topics

* link:simple-microservice-part1[{simple-microservice-part1}]
* link:simple-microservice-part2[{simple-microservice-part2}]
* link:simple-microservice-database-part1[{simple-microservice-database-part1}]
* link:simple-microservice-database-part2[{simple-microservice-database-part2}]
* link:simple-microservice-jms-part1[{simple-microservice-jms-part1}]
* link:simple-microservice-jms-part2[{simple-microservice-jms-part2}]
* link:simple-microservice-infinispan-part1[{simple-microservice-infinispan-part1}]
* link:simple-microservice-infinispan-part2[{simple-microservice-infinispan-part2}]
* link:get-enterprise-ready[{get-enterprise-ready}]

[[references]]
== References

* https://microprofile.io/specifications/microprofile-config/[Eclipse MicroProfile Config]

