---
layout: post
title:  "WildFly 23.0.1 is released!"
aliases: [/news/2021/04/14/WildFly2301-Released]
date:   2021-04-14
tags:   announcement release
author: bstansberry
description: WildFly 23.0.1.Final is now available for download.
---

WildFly 23.0.1.Final is now available link:https://wildfly.org/downloads[for download].

It's been about a month since the WildFly 23 release, so we've done a bug fix update, WildFly 23.0.1.

== WildFly Preview and Jakarta EE 9.0

The big news in this release is the fact that the link:https://docs.wildfly.org/23/WildFly_and_WildFly_Preview.html[WildFly Preview variant] of the server passes the TCKs for the Jakarta EE 9.0 link:https://github.com/wildfly/certifications/blob/EE9/WildFly_23.0.1.Final/jakarta-full-platform.adoc[Full Platform] and the link:https://github.com/wildfly/certifications/blob/EE9/WildFly_23.0.1.Final/jakarta-web-profile.adoc[Web Profile]. We've sent a link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/326[compatibility certification request for the Full Platform] to Eclipse. We'd previously been able to link:https://github.com/eclipse-ee4j/jakartaee-platform/issues/315[certify compatibility with the Web Profile] for WildFly Preview 23.0.0.

I'm very excited about this achievement and am so proud of the great WildFly contributors who made it happen, particularly Scott Marlow, Richard Opalka, Jean-Francois Denise, Geoffrey DeSmet, Emmanuel Hugonnet, Farah Juma, Jason Lee, Jim Ma, Matej Novotny, Flavia Rainone and Parul Sharma.

As is described in the link:https://docs.wildfly.org/23/WildFly_and_WildFly_Preview.html[WildFly docs], WildFly Preview is a tech preview variant of the server meant to allow our community to get an early look at new things we're looking to eventually bring into the standard WildFly variant. Currently, the main (but not only) difference from standard WildFly is support of Jakarta EE 9 instead of EE 8.

WildFly Preview is not a compatible Jakarta EE 8 or MicroProfile Platform 4.0 implementation, although we do expect most apps using the EE 8 and MP 4 APIs to run well on it.

WildFly Preview is available on the link:https://wildfly.org/downloads[download page], next to the standard WildFly download links for the same version. Look for the 'WildFly Preview EE 9 Distribution' links.

== Release Notes

The full list of issues resolved in WildFly 23.0.1 is available link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12354096[here]. Issues resolved in the WildFly Core update included with WildFly 23.0.1 are available link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12315422&version=12354209[here].


Enjoy!
