---
layout: post
title:  "How to contribute to WildFly"
date:   2024-03-01
tags:   WildFly contribution
author: rchakrab
description: Article about How to contribute to WildFly.
---

Welcome to the world of WildFly contributions, a place where your skills can make a real impact! If you're eager to dive in but not sure where to start, this guide is here to simplify the process for you. Whether you're new to open source or just getting acquainted with WildFly, we've got your back.

In the upcoming sections, we'll walk you through the essential steps, providing insights into the WildFly ecosystem and equipping you with the tools and knowledge needed to actively participate in its development. From setting up your development environment to engaging with the vibrant community, each step is a gateway to not only enhancing your technical skills but also fostering connections within a community passionate about open-source excellence. Join us as we explore how you can navigate the wild and make your mark in the world of WildFly contributions.

== Get Acquainted with WildFly

The first step in contributing to WildFly is to familiarize yourself with the project. Visit the WildFly https://github.com/wildfly/wildfly[GitHub repository]. Explore the project structure, review the source code, and read the https://docs.wildfly.org/[latest documentation] available in the repository. The documentation provides valuable insights into building, configuring, and deploying applications with WildFly.

== Set Up Your Development Environment and Install WildFly

Before installing the latest version of WildFly, there are a few prerequisites:

* Check that you have a JDK on your machine—JDK 11 or higher recommended to start WildFly. You can use the open source JDK called https://openjdk.org/[OpenJDK]. Once you install the JDK, set the JAVA_HOME environment variable.

* Ensure you have Maven 3.6.0 or higher installed. You can download Maven from https://maven.apache.org/download.cgi[here] and set the environment variables.

* After loading both the variables, check the versions of JDK and Maven like below.

....
$ java -version
openjdk version “11.0.9” 2020-10-20 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
....

....
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) Maven home: /usr/share/maven
Java version: 11.0.9, vendor: AdoptOpenJDK, runtime: /usr/lib64/adoptopenjdk
Default locale: en_US, platform encoding: UTF-8
OS name: “linux”, version: “5.9.1”, arch: “amd64”, family: “unix”
....

There are many ways you can install WildFly, including unzipping our traditional download zip, provisioning a custom installation using Galleon, or building a bootable jar. The official https://docs.wildfly.org/24/Installation_Guide.html[installation guide] helps you identify the kind of WildFly installation that best fits your application’s deployment needs.

== Create an Issue or Follow the JIRA

WildFly uses JIRA for issue tracking. You can find the list of issues and tasks on the https://issues.redhat.com/projects/WFLY[WildFly JIRA dashboard]. If you encounter a bug, have a feature request, spot something in the documentation that could be improved or spot something missing in the documentation, or want to contribute in any way, create a new issue on JIRA. Alternatively, you can pick an existing issue or go through https://issues.redhat.com/issues/?filter=12403174[good first issues] that aligns with your interests or skills.

== Select an Issue and Send a Pull Request:

Once you've identified an issue you'd like to work on, https://github.com/wildfly/wildfly/fork[fork the WildFly repository], create a new branch, and start working on the issue. Make your changes, commit them, and push the changes to your forked repository. Finally, submit a pull request to the main WildFly repository. For better understanding you can also follow the official https://docs.wildfly.org/31/Hacking_On_WildFly.html#getting-started[getting started guide]. Make sure to follow the https://github.com/wildfly/wildfly/blob/main/CODE_OF_CONDUCT.md[code of conduct] and https://github.com/wildfly/wildfly/blob/main/CONTRIBUTING.md[contribution guidelines] to ensure a smooth review process.

== Participate in Code Review

Code review is a crucial aspect of any open-source project. Engage in discussions with other contributors, address feedback, and iterate on your changes. This collaborative process helps maintain code quality and ensures that contributions align with the project's standards.

== Engage with the Community

WildFly has a diverse and active community of developers, users, and contributors. Join the discussion on the WildFly google group - wildfly@googlegroups.com or via the Zulip https://wildfly.zulipchat.com/#narrow/stream/196266-wildfly-user[wildfly-user], https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers[wildfly-developer] channels. We are also present on https://twitter.com/WildFlyAS[X] and https://www.youtube.com/@WildFlyAS[YouTube], you can follow us there as well. Participate in community events, webinars, and conferences related to WildFly. Engaging with the community not only enhances your understanding of the project but also opens doors for collaboration and mentorship.

Contributing to WildFly is a rewarding experience that allows you to be part of a thriving open-source community. By following these steps, you can make meaningful contributions to the project, enhance your skills, and connect with like-minded individuals who share a passion for open-source development. Remember, every contribution, no matter how small, makes a valuable impact on the success of the WildFly project.
