---
layout: post
title:  "How to Connect with the WildFly Community"
aliases: [/news/2024/05/31/How-to-connect-with-WildFly-community]
date:   2024-05-31
tags:   WildFly Community
author: rchakrab
description: Article about How to connect with the WildFly Community.
---

WildFly is an open-source, production-ready, flexible and lightweight application server, offering all the necessary features to run and deploy Java applications. Connecting with the WildFly community can provide valuable support, enhance your understanding of the server, and offer opportunities to contribute to the project. Here's how you can get involved:

== Get an Idea about WildFly
=== Explore the WildFly Website

Visit WildFly's official https://www.wildfly.org/[website] to access comprehensive documentations, guides, downloads, and the latest news. The website serves as your primary resource for understanding and using WildFly effectively.

=== Get Started with WildFly
Begin by downloading https://www.wildfly.org/downloads/[WildFly] and following the https://www.wildfly.org/get-started/[getting started guide] on the website. This guide walks you through installation, initial configuration, and deploying a sample application, setting you up for success with your first WildFly server.

=== Fork the WildFly Repository on GitHub and Play with It
Explore WildFly's https://github.com/wildfly/wildfly[source code] by https://github.com/wildfly/wildfly/fork[forking] the repository on GitHub. Clone your forked repository to your local machine, experiment with the code, and understand the inner workings of WildFly. This hands-on approach can deepen your knowledge and potentially lead to contributions to the project. You can also go through the article on https://www.wildfly.org/news/2024/03/01/How-to-contribute-to-WildFly/[How to contribute to WildFly].

== Engage with the WildFly Community
=== Engage in the WildFly Forums
Participate in the https://groups.google.com/g/wildfly[WildFly Google Group] to ask questions, share knowledge, and engage with other users and developers. The forum is a valuable platform for seeking help, providing answers, and staying updated with announcements and community discussions. You can also chat with the WildFly community members as well as with contributors via our official https://wildfly.zulipchat.com/[Zulip] chatroom and for discussions about using WildFly, try the https://wildfly.zulipchat.com/#narrow/stream/196266-wildfly-user[wildfly-user stream] in the chatroom.

=== Follow WildFly on Social Media
Stay informed and connected by following WildFly on social media platforms. Follow us on https://x.com/WildFlyAS[X] and https://fosstodon.org/@wildflyas[Mastodon] for quick updates, announcements, and subscribe to the WildFly https://www.youtube.com/@WildFlyAS[YouTube] channel for video tutorials, webinars, and conference talks.

=== Use WildFly RSS Feeds
Stay updated with the latest news, releases, and blog posts by subscribing to WildFly's https://www.wildfly.org/feed.xml[RSS feed]. This ensures you never miss important announcements and updates from the WildFly project.

=== Attend WildFly Community Events
Participate in WildFly community events such as mini-conferences and webinars. These events offer learning opportunities through sessions and workshops by experts, networking with other users and developers, and community-building activities. Keep an eye on the WildFly website and social media channels for announcements about upcoming events.

== Provide and Receive Support
=== Ask for Help
Don’t hesitate to seek support through forums, mailing lists, or social media channels. The WildFly community is active and responsive, making it a great resource for troubleshooting and advice.

=== Offer Help
Share your knowledge and expertise to help others in the community. By answering questions and providing guidance, you contribute to the collective knowledge base.

=== Submit Code or Contribute to Documentation
WildFly uses JIRA for issue tracking. You can find the list of issues and tasks on the https://issues.redhat.com/projects/WFLY/issues[WildFly JIRA dashboard]. If you've made improvements or fixed bugs in your forked repository, consider submitting pull requests to contribute back to the WildFly project. You can also visit the WildFly official https://docs.wildfly.org/[documentation] and feel free to suggest improvements, or directly contributing updates and corrections. Your contributions can help improve WildFly for everyone.

Connecting with the WildFly community enriches your experience with the platform. By exploring the website, engaging in forums, following on social media, attending events, and participating in support and contributions, you become an integral part of the vibrant WildFly ecosystem. Join the community today and help shape the future of enterprise Java applications!
