---
layout: post
title:  "Save the Date: WildFly Mini Conference on March 25th, 2025"
aliases: [/news/2025/03/19/WildFly-mini-conference-2025-save-the-date]
date:   2025-03-19
tags:   wildfly announcement conference wildfly-mini-conference
author: rchakrab
description: Save the Date -- WildFly Mini Conference March 25th
---

Hello, WildFly Community!

We are excited to announce that the WildFly Mini Conference is scheduled for March 25th, 2025! Building on the success of our previous events, we’re looking forward to another day of insightful discussions, community engagement, and deep dives into the latest in enterprise Java and WildFly development.

This year’s conference will focus on key topics shaping the future of WildFly and enterprise Java, including:

* *Quick Prototyping with WildFly* – Learn how to efficiently build and test applications using WildFly.
* *WildFly Day One Operations with Ansible Automation* – Discover best practices for deploying and managing WildFly with Ansible.
* *Everything about Jakarta EE TCKs in twenty minutes* – A concise session covering the essentials of Jakarta EE compatibility testing.
* *WildFly in a Vendor-Neutral Foundation* – Exploring the ecosystem and collaboration opportunities for WildFly.
* *WildFly AI Feature Pack: Deploying an MCP Server* – Learn how the WildFly AI Feature Pack enables intelligent middleware capabilities and enhances application deployments with AI-driven optimizations.

==== 📅 Date: Tuesday, March 25, 2025
==== ⏰ Time: 14:00 - 18:00 UTC
==== 🔗 Live stream: link:https://www.youtube.com/live/d8IExBP7rxw[YouTube Live]

Make sure to click "Notify me" on YouTube to receive reminders before the event starts.

This conference is a great opportunity for Java developers, middleware engineers, and open-source enthusiasts to explore the future of WildFly and enterprise Java. For more details, checkout our link:https://www.wildfly.org/events/wmc-202503.html[conference page]. We look forward to seeing you online for another great WildFly Mini Conference!








