---
layout: post
title:  "New WildFly 37 Beta release"
aliases: [/news/2025/06/26/WildFly37Beta-released/]
date:   2025-06-26
tags:   announcement release
author: darranl
description: WildFly 37 Beta is now available for download.
---

We're excited to announce the release of WildFly 37.0.0.Beta1! This beta release, available for download from https://wildfly.org/downloads, includes new features and several enhancements, alongside numerous component upgrades.

== Key Highlights in this Beta Release:

=== New Features:

* Artemis commit-interval attribute for scaledown: WildFly 37 Beta 1 exposes the Artemis commit-interval attribute for scaledown.
* The /core-service=platform-mbean resources have been evolved to expose new platform MXBeans, attributes and operations.

=== Enhancements:

* The tasks-jsf quickstart now uses Glow.
* GPG detached signatures are now included with uploads at release time.

The following commands demonstrate how to verify the GPG signature of the WildFly distribution:

[source,console]
----
$ gpg --keyserver keyserver.ubuntu.com --recv-keys E85C11F6
$ gpg --verify wildfly-37.0.0.Beta1-src.tar.gz.asc wildfly-37.0.0.Beta1-src.tar.gz
gpg: Signature made Wed 25 Jun 2025 14:33:44 BST
gpg:                using EDDSA key 245404A11575A55D6A41107E2D52D4ACE85C11F6
gpg: Good signature from "Darran Andrew Lofthouse <darran.lofthouse@jboss.com>" [unknown]
gpg:                 aka "Darran Andrew Lofthouse <darran.lofthouse@redhat.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2454 04A1 1575 A55D 6A41  107E 2D52 D4AC E85C 11F6
----

Contributors to WildFly publish their GPG keys on the https://wildfly.org/contributors/pgp[Contributor PGP Information], which
includes the fingerprint to aid verification.

=== Component Upgrades:

This release includes a significant number of component upgrades, ensuring WildFly remains current with the latest technologies and provides improved performance and security. Some notable upgrades include:

* Vert.x to 4.5.15.
* Hibernate ORM to 6.6.18.Final (and 7.0.2.Final for WildFly Preview).
* Micrometer to 1.15.0.
* EclipseLink to 4.0.6.
* SmallRye Fault Tolerance to 6.9.1.
* Apache Santuario XML Security for Java to 3.0.6.
* JBoss Universe Producers to 1.3.14.
* JBoss Metadata to 16.1.0.Final.
* Netty to 4.1.122.Final.
* Velocity Engine to 2.4.1.
* WildFly Clustering to 7.0.5.Final.
* Infinispan to 15.2.4.Final.
* JGroups to 5.4.
* Apache Artemis to 2.41.0.
* WildFly Core to 29.0.0.Beta6.
* HAL to 3.7.12.Final.
* Byteman to 4.0.25.
* JBossWS-CXF to 7.3.3.Final.
* Narayana to 7.2.2.Final.
* zstd-jni to 1.5.7-3.
* WildFly Licenses Plugin to 2.4.2.Final.
* FasterXML Jackson to 2.18.4.
* SmallRye Common to 2.12.0.
* Hibernate Search to 8.0.0.Final (in WildFly preview).
* Weld to 5.1.6.Final and 6.0.3.Final.
* Hibernate Validator to 9.0.1.Final (in WildFly preview).
* Expressly to 6.0.0 (in WildFly preview).
* Apache CXF to 4.0.8.
* Commons-Beanutils to 1.11.0, which resolves CVE-2025-48734.
* WildFly Channel Maven Plugin to 1.0.25.
* WildFly HTTP Client to 2.1.1.Final.
* Narayana LRA to 1.0.1.Final.
* Arquillian BOM to 1.9.5.Final.
* Arquillian Testcontainers to 1.0.0.Alpha4.
* Caffeine to 3.2.1.
* Apache Kafka to 3.9.1.
* SmallRye OpenAPI to 4.0.11.
* Nimbus Jose JWT to 10.3.
* Artemis WildFly Integration to 2.0.4.Final.
* MVC Krazo integration to 2.0.0.Final.
* OWASP Dependency Check Plugin to 12.1.3.

For a complete list of bug fixes, tasks, sub-tasks, and other changes, please refer to the link:https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12449162[full release notes]. We encourage the community to test this beta release and provide feedback to help us stabilize WildFly 37.
