---
layout: post
title:  "WildFly 37 is released!"
aliases: [/news/2025/08/04/WildFly37Released]
date:   2025-08-04
tags:   announcement release
author: bstansberry
description: WildFly 37 Final is now available for download.
---

I'm pleased to announce that the new WildFly and WildFly Preview 37.0.0.Final releases are available for download at https://wildfly.org/downloads[https://wildfly.org/downloads, window=_blank], The Galleon feature packs for WildFly 37 are available in https://repository.jboss.org/nexus/[ the JBoss Maven repository, window=_blank].

NOTE: We expect it will be another day before the 37 artifacts are available in Maven Central.

[[new_and_notable]]
== New and Notable

This quarter was primarily devoted to bug fixing and clearing of technical debt. A lot of our focus was on working on the https://www.wildfly.org/news/2025/04/30/WildFly-joins-Commonhaus/[transition of WildFly to Commonhaus sponsorship, window=_blank] as well as adapting to the transition to Nexus 3 in the https://repository.jboss.org/nexus/[Maven repository where we deploy most WildFly artifacts, window=_blank]. The latter in particular has been a major effort.

We did add one small feature this quarter:

* The `messaging-activemq` subsystem https://docs.wildfly.org/wildfly-proposals/messaging/WFLY-20512_expose_scale_down_commit_interval.html[added the `scale-down-commit-interval` attribute, window=_blank] to its `ha-policy` resource to let users define the number of messages in a transaction batch when transferring them to another node during a scale down. This setting can help avoid OOME issues during scale down.

== Supported Specifications

=== Jakarta EE

Standard WildFly 37 is a compatible implementation of the EE 10 link:https://jakarta.ee/specifications/platform/10/[Platform, window=_blank] as well as the link:https://jakarta.ee/specifications/webprofile/10/[Web Profile, window=_blank] and the link:https://jakarta.ee/specifications/coreprofile/10/[Core Profile, window=_blank]. WildFly is EE 10 Platform, Web Profile and Core Profile compatible when running on Java SE 17 and Java SE 21.

Evidence supporting our certification is available in the link:https://github.com/wildfly/certifications/tree/EE10[WildFly Certifications, window=_blank] repository on GitHub:
[cols=",",options="header"]
|=======================================================================
|Specification |Compatibility Evidence
.2+.<| Jakarta EE 10 Full Platform
| link:https://github.com/wildfly/certifications/blob/EE10/WildFly_37.0.0.Final/jakarta-full-platform-jdk17.adoc#tck-results[SE 17, window=_blank]
| link:https://github.com/wildfly/certifications/blob/EE10/WildFly_37.0.0.Final/jakarta-full-platform-jdk21.adoc#tck-results[SE 21, window=_blank]
.2+.<|  Jakarta EE 10 Web Profile
| link:https://github.com/wildfly/certifications/blob/EE10/WildFly_37.0.0.Final/jakarta-web-profile-jdk17.adoc#tck-results[SE 17, window=_blank]
| link:https://github.com/wildfly/certifications/blob/EE10/WildFly_37.0.0.Final/jakarta-web-profile-jdk21.adoc#tck-results[SE 21, window=_blank]
.2+.<| Jakarta EE 10 Core Profile
| link:https://github.com/wildfly/certifications/blob/EE10/WildFly_37.0.0.Final/jakarta-core-jdk17.adoc#jakarta-core-profile-1001-tck-java-se-17-results[SE 17, window=_blank]
| link:https://github.com/wildfly/certifications/blob/EE10/WildFly_37.0.0.Final/jakarta-core-jdk21.adoc#jakarta-core-profile-1001-tck-java-se-21-results[SE 21, window=_blank]
|=======================================================================


=== MicroProfile

Standard WildFly 37 supports https://microprofile.io/2024/08/22/microprofile-7-0-release/[MicroProfile Platform 7.0, window=_blank], along with several other MicroProfile specifications that are not part of MicroProfile Platform. The full listing is available in the link:https://docs.wildfly.org/37/Getting_Started_Guide.html[Getting Started Guide, window=_blank].

link:https://github.com/wildfly/certifications/blob/MP7.0/WildFly_37.0.0.Final/microprofile-7.0/microprofile-7.0-full-certification.adoc[Compatibility evidence, window=_blank] for the specifications that are part of MicroProfile 7.0 can be found in the WildFly Certifications repository on GitHub.


[[preview-ee11]]
=== WildFly Preview and EE 11

Since the https://www.wildfly.org/news/2024/04/25/WildFly32-Released/[WildFly 32 release, window=_blank], we are using WildFly Preview to provide a look at what we're doing for Jakarta EE 11 support.  The EE 11 Platform and Web Profile specifications won't go GA before later this year. But there are milestone, Release Candidate and Final releases of many EE 11 specs and implementations available, so we are providing those in WildFly Preview. This means for a number of EE APIs, WildFly Preview no longer provides an EE 10 compatible implementation.

However, for a number of specifications that are planning changes for EE 11 we are still offering the EE 10 variant. In future releases we'll shift those to the EE 11 variants.

The link:https://jakarta.ee/specifications/coreprofile/11/[EE 11 Core Profile specification, window=_blank] went GA last November and WildFly Preview 37 supports that profile.

The Jakarta EE 11 link:https://jakarta.ee/specifications/platform/11/[Platform, window=_blank] and link:https://jakarta.ee/specifications/webprofile/10/[Web Profile, window=_blank] went GA earlier this year. We are working on completing our implementation of these in WildFly Preview, for eventual incorporation in standard WildFly.

Full details on the EE specification versions provided by WildFly Preview can be found in https://docs.wildfly.org/37/WildFly_and_WildFly_Preview.html#ee-11-support-in-wildfly-preview[the WildFly 37 documentation, window=_blank].


== Java SE Support

Our recommendation is that you run WildFly 37 on Java SE 21, as that is the latest LTS JDK release where we have completed the full set of testing we like to do before recommending a particular SE version. WildFly 37 also is heavily tested and runs well on Java 17.

Our recommendation of SE 21 over SE 17 is solely because as a general principle we recommend being on later LTS releases, not because of any problems with WildFly on SE 17.

While we recommend using an LTS JDK release, I do believe WildFly runs well on SE 24. By runs well, I mean the main WildFly testsuite runs with no more than a few  link:https://issues.redhat.com/issues/?filter=12460273[failures in areas not expected to be commonly used, window=_blank]. We want developers who are trying to evaluate what a newer JVM means for their applications to be able to look to WildFly as a useful development platform. We've also had good results with tests on Linux of an EA release of SE 25 (Oracle 25-ea+10-1084).

Please note that WildFly runs in classpath mode.

[[incompatibilities]]
== Incompatible Changes

There are a few incompatible changes in WildFly 37 that may affect some users:

* We removed the `jgroups-udp-fd` and `jgroups-tcp-fd` socket bindings from our out-of-the-box configuration files in favor of a single `jgroups-fd` socket binding. If you are customizing our standard configs you may need to adapt your customization.
* If you develop low-level management clients for WildFly, you may be affected by a change to the https://github.com/wildfly/wildfly-core/blob/29.0.0.Final/controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClient.java[ModelControllerClient, window=_blank] interface. We've changed the return type from the `executeAsync` and `executeOperationAsync` methods from the `org.jboss.threads.AsyncFuture` interface to Java SE's `java.util.concurrent.CompletableFuture`. Both of those are `java.util.concurrent.Future` sub-interfaces, so if all you were using was the `Future` API this may not affect you.
* You can manage a WildFly instance with Java Mission Control by integrating our `jboss-client.jar` into your JMC installation, typically by dropping the jar in your JMC installation's `Eclipse/dropins` folder. The mechanism JMC provides for this integration changed incompatibly between JMC 8 and JMC 9, and it's not possible for us to support both in the same `jboss-client.jar`. For WildFly 37 we switched to supporting the JMC 9+ mechanism, so the 37 jar can't be integrated into JMC 8. However, a JMC 8 installation using an older version of `jboss-client.jar` will work fine for managing a WildFly 37 server. A JMC 9 integration can manage an older WildFly as well.

[[contributors]]
== New and Noteworthy Contributors

WildFly gets great contributions from so many people. Let's thank a few of them.

Cody Lerum provided an excellent reproducer for https://issues.redhat.com/browse/WFLY-20646[WFLY-20646, window=_blank] / https://hibernate.atlassian.net/browse/HHH-19476[HHH-19476, window=_blank], a problem that had been troubling a number of Hibernate users. The reproducer quickly led to a fix. Beyond this, Cody always provides great feedback. You're the best, Cody!

David Hladky has been going way above and beyond working through the transition of https://repository.jboss.org/nexus/[repository.jboss.org, window=_blank] to Nexus 3. Thank you, David!

link:https://github.com/pferraro[Paul Ferraro, window=_blank] provided great inputs about how WildFly and other projects should deploy to the new https://repository.jboss.org/nexus/[repository.jboss.org, window=_blank]. Paul's also been doing yeoman's work on transitioning a number of our subsystem implemenations to the modernized subsystem development framework he created. Thank you, Paul!

link:https://github.com/jasondlee[Jason Lee, window=_blank] migrated this website from Jekyll to the rockin' https://github.com/quarkiverse/quarkus-roq[Quarkus Roq, window=_blank]. Much appreciated, Jason!

== Release Notes

The full WildFly 37 release notes are link:https://github.com/wildfly/wildfly/releases/tag/37.0.0.Final[available in GitHub, window=_blank].  Issues fixed in the underlying WildFly Core 29.0.0 release are listed in the link:https://issues.redhat.com/issues/?filter=12475573[WildFly Core JIRA, window=_blank].

Please try it out and give us your feedback, in the link:https://groups.google.com/g/wildfly[WildFly google group, window=_blank], link:https://wildfly.zulipchat.com/#narrow/stream/196266-wildfly-user[Zulip, window=_blank] or link:https://issues.redhat.com/projects/WFLY/summary[JIRA, window=_blank].

Onward to WildFly 38!

Best regards,

Brian
