---
layout: post
title:  "A2A Java SDK for Jakarta 0.3.0.Final is released!"
aliases: [/news/2025/11/06/A2A_SDK_Jakarta_0.3.0.Final-Released/]
date:   2025-11-06
tags:   announcement release generative-ai a2a agent wildfly
author: kkhan
description: A2A Java SDK for Jakarta 0.3.0.Final is released.
---

I am pleased to announce the 0.3.0.Final release of the A2A Java SDK for Jakarta. You can find the release https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta/releases/tag/v0.3.0.Final[here], and it supports version https://a2a-protocol.org/v0.3.0/specification/[0.3.0 of the A2A Protocol Specification].

Since the https://www.wildfly.org/news/2025/09/19/A2A-Java-SDK-for-Jakarta-0-3-0-Beta1-is-released/[0.3.1.Beta1] release, there haven't been big changes on our side, but we are now aligned with version 0.3.2.Final of the https://github.com/a2aproject/a2a-java[A2A Java SDK]. A lot of work has taken place there since the previous version of the A2A Java SDK we aligned with which was 0.3.0.Beta1.

You can find the pulled in changes in the A2A Java SDK release notes for each version here:

* https://github.com/a2aproject/a2a-java/releases/tag/v0.3.0.Beta2[v0.3.0.Beta2]
* https://github.com/a2aproject/a2a-java/releases/tag/v0.3.0.Final[v0.3.0.Final]
* https://github.com/a2aproject/a2a-java/releases/tag/v0.3.1.Final[v0.3.1.Final]
* https://github.com/a2aproject/a2a-java/releases/tag/v0.3.2.Final[v0.3.2.Final]

Please see the A2A Java SDK for Jakarta https://www.wildfly.org/news/2025/09/19/A2A-Java-SDK-for-Jakarta-0-3-0-Beta1-is-released/[0.3.1.Beta1] release announcement for how to get started with the SDK.

== Future Plans
We will continue to align with the A2A SDK for Java, which is currently working towards supporting 0.4.0 of the A2A Protocol Specification. Note that the work on 0.4.0 of the specification has not finished yet.

Also, it is worth pointing out that for WildFly users, the A2A Java SDK for Jakarta currently relies on bundling the jars from the two SDKs, as well as their dependencies, into your application deployment archive. We would like to create a WildFly feature pack for this, which would follow the normal WildFly pattern of enabling a subsystem which would make all the A2A libraries available automatically to deployments, thus removing the need to bundle them in your application.

However, we have decided that the https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta[wildfly-extras/a2a-java-sdk-server-jakarta] repository is not the correct place for such a feature pack, since it is meant to be used by people wanting to integrate in other Jakarta runtimes. Instead, we are considering adding it to the https://github.com/wildfly-extras/wildfly-ai-feature-pack[WildFly AI Feature Pack]. This will be announced separately when it happens.

== Get involved
* If you have any issues with the SDK, please open an https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta/issues[issue]. Also, https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta/pulls[pull requests] are welcome!