---
layout: post
title:  "A2A Java SDK for Jakarta 0.3.0.Beta1 is released!"
aliases: [/news/2025/09/15/A2A_SDK_Jakarta_0.3.0.Beta1-Released/]
date:   2025-09-15
tags:   announcement release generative-ai a2a agent wildfly
author: kkhan
description: A2A Java SDK for Jakarta 0.3.0 is released.
---

Following the release of version 0.3.0.Beta1 of the A2A Java *SDK TODO - link to announcement*, I am excited to announce the release of the corresponding 0.3.0.Beta1 release of the A2A Java SDK for Jakarta. *TODO link to tag*

A2A stands for https://a2a-protocol.org/latest/[Agent2Agent Protocol], which is a protocol hosted under the Linux Foundation to enable seamless communication and collaboration between AI Agents implemented using any language/technology stack.

The https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta[A2A Java SDK for Jakarta] consumes the http://github.com/a2aproject/a2a-java[A2A Java SDK]. The reason for the split is that the A2A Java SDK is meant to be server agnostic. While it provides an implementation for Quarkus as its reference implementation, so that it has something to run tests and the https://github.com/a2aproject/a2a-tck[A2A Protocol TCK] against, it was decided that integrations with other runtimes should be developed externally. These are listed in the 'Server integrations' section https://github.com/a2aproject/a2a-java?tab=readme-ov-file#server-integrations[here].

== What is new

*TODO Link to change list*

We have done a lot of reorganisation of both projects so it is more modular.

Also, following some upgrades to our internal infrastructure, we are able to deploy the artifacts to https://central.sonatype.com/search?namespace=org.wildfly.a2a[Maven Central] under the `org.wildfly.a2a` groupId.

Aside from that the major new feature is the inclusion of the [`gRPC`] transport, which relies on the https://github.com/wildfly-extras/wildfly-grpc-feature-pack[WildFly gRPC Feature Pack].

We pass the TCK for both `gRPC` and the original `JSON-RPC` transport, and the final transport from the 0.3.0 https://a2a-protocol.org/latest/specification/[A2A Protocol Specification], `HTTP+JSON` should be done in time for the final 0.3.0 release.

A simple example showing how to package an agent for use with both transports can be found https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta/tree/main/examples/simple[here].

== How to use
Rather than going into a full example here, the starting point is to include one or both of the following dependencies in your application:
* `org.wildfly.a2a:a2a-java-sdk-jakarta-jsonrpc:0.3.0.Beta1` - to enable the `JSON-RPC` protocol
* `org.wildfly.a2a:a2a-java-sdk-jakarta-grpc:0.3.0.Beta1` - to enable the `gRPC` protocol.

The https://github.com/wildfly-extras/a2a-java-sdk-server-jakarta/tree/main/examples/simple[simple example] provides more guidance for how to manage the dependencies.

Note that the simple example is more of a "Hello world" type application focussed on how to package your application for use with the A2A Java SDK for Jakarta.

Once you have packaged your application, see the examples in the https://github.com/a2aproject/a2a-java/tree/main/examples/helloworld[a2a-java] repository, and the https://github.com/a2aproject/a2a-samples/tree/main/samples/java/agents[Java samples in the a2a-samples] repository for how to actually implement agents that communicate with each other. You can then, for example, try to replace one of those agents with one running on WildFly.


== What is coming next?

As mentioned, we need to support the `HTTP+JSON` transport to be fully compliant with the 0.3.0 version of the protocol. We aim to have this done for the final 0.3.0 release.

Also, we would like to investigate if we can provide the dependencies in a nicer way so all the exclusions seen in the current version of the sample https://github.com/a2aproject/a2a-java/issues/268[are no longer required].



