---
layout: post
title:  "WildFly in a Foundation"
date:   2025-02-03
tags:   announcement foundation
author: bstansberry
description: WildFly is considering moving a vendor-neutral foundation.
---

In the last two years we've been putting a lot of effort into improving how the WildFly project interacts with our community, including adding new communication channels like our link:https://www.wildfly.org/conference/[Mini Conferences, window=_blank], adding new https://www.wildfly.org/guides/[user guides, window=_blank] and creating a transparent https://docs.wildfly.org/wildfly-proposals/FEATURE_PROCESS.html[feature development process, window=_blank]. WildFly has been a successful project for a long time now, and I believe that's largely because we are passionate about serving our community.

To help us continue on this path, we are considering moving WildFly to a vendor-neutral software foundation. Our hope is that by doing this we could further expand our community, improve our openness and transparency, refresh our governance model, and encourage more participation by contributors not affiliated with Red Hat.

== Important Considerations

Moving to a foundation is not a trivial task, so it's critical that the choice we make is a net benefit to our community. To help ensure this, there are a number of key factors we're looking at when evaluating what foundation would be the best fit:

* Flexibility to continue shipping third-party components using a wide array of Open Source Initiative (OSI)-approved Open Source licences.

* Maintain as much as possible our current release processes.

* Retain independence in decision making, particularly on technical matters.

== Support and Alignment with Red Hat Values

Red Hat is dedicated to participating in and supporting vendor-neutral collaboration projects, such as the Linux kernel, Kubernetes, and OpenJDK; doing so is part of the company's DNA. Red Hat business leaders are fully supportive of this move.

== Community Feedback

We'd love to hear your thoughts on this. Let us know what you're thinking either on the link:https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/[developer mail list, window=_blank], in the link:https://groups.google.com/g/wildfly[WildFly google group, window=_blank] or in link:https://wildfly.zulipchat.com/#narrow/channel/174184-wildfly-developers[Zulip, window=_blank]

Best regards,

Brian
